package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysEntDetail<M extends BaseSysEntDetail<M>> extends Model<M> implements IBean {

	/**
	 * 用户详情ID
	 */
	public void setDetailId(java.lang.Long detailId) {
		set("detail_id", detailId);
	}
	
	/**
	 * 用户详情ID
	 */
	public java.lang.Long getDetailId() {
		return getLong("detail_id");
	}
	
	/**
	 * 用户ID
	 */
	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户ID
	 */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}
	
	/**
	 * 企业用户密码
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * 企业用户密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	/**
	 * 密码盐值
	 */
	public void setSalt(java.lang.String salt) {
		set("salt", salt);
	}
	
	/**
	 * 密码盐值
	 */
	public java.lang.String getSalt() {
		return getStr("salt");
	}
	
	/**
	 * 企业名称
	 */
	public void setEntName(java.lang.String entName) {
		set("ent_name", entName);
	}
	
	/**
	 * 企业名称
	 */
	public java.lang.String getEntName() {
		return getStr("ent_name");
	}
	
	/**
	 * 企业地址
	 */
	public void setEntAddress(java.lang.String entAddress) {
		set("ent_address", entAddress);
	}
	
	/**
	 * 企业地址
	 */
	public java.lang.String getEntAddress() {
		return getStr("ent_address");
	}
	
	/**
	 * 企业简称
	 */
	public void setEntShortName(java.lang.String entShortName) {
		set("ent_short_name", entShortName);
	}
	
	/**
	 * 企业简称
	 */
	public java.lang.String getEntShortName() {
		return getStr("ent_short_name");
	}
	
	/**
	 * 统一社会信用代码
	 */
	public void setEntCreditCode(java.lang.String entCreditCode) {
		set("ent_credit_code", entCreditCode);
	}
	
	/**
	 * 统一社会信用代码
	 */
	public java.lang.String getEntCreditCode() {
		return getStr("ent_credit_code");
	}
	
	/**
	 * 企业类型：平台字典索引
	 */
	public void setEntType(java.lang.String entType) {
		set("ent_type", entType);
	}
	
	/**
	 * 企业类型：平台字典索引
	 */
	public java.lang.String getEntType() {
		return getStr("ent_type");
	}
	
	/**
	 * 企业类型：类型名称，可自定义
	 */
	public void setEntTypeStr(java.lang.String entTypeStr) {
		set("ent_type_str", entTypeStr);
	}
	
	/**
	 * 企业类型：类型名称，可自定义
	 */
	public java.lang.String getEntTypeStr() {
		return getStr("ent_type_str");
	}
	
	/**
	 * 企业电话
	 */
	public void setEntTelphone(java.lang.String entTelphone) {
		set("ent_telphone", entTelphone);
	}
	
	/**
	 * 企业电话
	 */
	public java.lang.String getEntTelphone() {
		return getStr("ent_telphone");
	}
	
	/**
	 * 营业执照
	 */
	public void setEntBusinessLicence(java.lang.String entBusinessLicence) {
		set("ent_business_licence", entBusinessLicence);
	}
	
	/**
	 * 营业执照
	 */
	public java.lang.String getEntBusinessLicence() {
		return getStr("ent_business_licence");
	}
	
	/**
	 * 企业头像
	 */
	public void setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
	}
	
	/**
	 * 企业头像
	 */
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}
	
	/**
	 * 头像原文件groupcode
	 */
	public void setSourceCode(java.lang.String sourceCode) {
		set("source_code", sourceCode);
	}
	
	/**
	 * 头像原文件groupcode
	 */
	public java.lang.String getSourceCode() {
		return getStr("source_code");
	}
	
	/**
	 * 头像原文件地址
	 */
	public void setSourceUrl(java.lang.String sourceUrl) {
		set("source_url", sourceUrl);
	}
	
	/**
	 * 头像原文件地址
	 */
	public java.lang.String getSourceUrl() {
		return getStr("source_url");
	}
	
	/**
	 * 企业认证账号： -1 未认证 0 待审核 1 营业执照通过 2 营业执照认证不通过
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 企业认证账号： -1 未认证 0 待审核 1 营业执照通过 2 营业执照认证不通过
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 企业编码/企业别名/组织编码/企业后缀
	 */
	public void setOrgCode(java.lang.String orgCode) {
		set("org_code", orgCode);
	}
	
	/**
	 * 企业编码/企业别名/组织编码/企业后缀
	 */
	public java.lang.String getOrgCode() {
		return getStr("org_code");
	}
	
	/**
	 * 当前账号是否是企业主账号 0、是 1、否
	 */
	public void setIsMainAccount(java.lang.Integer isMainAccount) {
		set("is_main_account", isMainAccount);
	}
	
	/**
	 * 当前账号是否是企业主账号 0、是 1、否
	 */
	public java.lang.Integer getIsMainAccount() {
		return getInt("is_main_account");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}
	
}
