package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends Model<M> implements IBean {

	/**
	 * 用户ID
	 */
	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户ID
	 */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}
	
	/**
	 * 广联云用户ID
	 */
	public void setAccountCloudId(java.lang.Long accountCloudId) {
		set("account_cloud_id", accountCloudId);
	}
	
	/**
	 * 广联云用户ID
	 */
	public java.lang.Long getAccountCloudId() {
		return getLong("account_cloud_id");
	}
	
	/**
	 * 广联云GlodonID
	 */
	public void setGlodonId(java.lang.Long glodonId) {
		set("glodon_id", glodonId);
	}
	
	/**
	 * 广联云GlodonID
	 */
	public java.lang.Long getGlodonId() {
		return getLong("glodon_id");
	}
	
	/**
	 * 真实姓名
	 */
	public void setNickname(java.lang.String nickname) {
		set("nickname", nickname);
	}
	
	/**
	 * 真实姓名
	 */
	public java.lang.String getNickname() {
		return getStr("nickname");
	}
	
	/**
	 * 是否认证 注: 0、已认证 1、未认证 2、审核中
	 */
	public void setIsMark(java.lang.Integer isMark) {
		set("is_mark", isMark);
	}
	
	/**
	 * 是否认证 注: 0、已认证 1、未认证 2、审核中
	 */
	public java.lang.Integer getIsMark() {
		return getInt("is_mark");
	}
	
	/**
	 * 是否锁定 注: 0、正常 1、锁定
	 */
	public void setIsLock(java.lang.Integer isLock) {
		set("is_lock", isLock);
	}
	
	/**
	 * 是否锁定 注: 0、正常 1、锁定
	 */
	public java.lang.Integer getIsLock() {
		return getInt("is_lock");
	}
	
	/**
	 * 是否黑名单 注：0、正常 1、黑名单
	 */
	public void setIsBlacklist(java.lang.Integer isBlacklist) {
		set("is_blacklist", isBlacklist);
	}
	
	/**
	 * 是否黑名单 注：0、正常 1、黑名单
	 */
	public java.lang.Integer getIsBlacklist() {
		return getInt("is_blacklist");
	}
	
	/**
	 * 是否激活 注：0、已激活 1、未激活
	 */
	public void setIsVerified(java.lang.Integer isVerified) {
		set("is_verified", isVerified);
	}
	
	/**
	 * 是否激活 注：0、已激活 1、未激活
	 */
	public java.lang.Integer getIsVerified() {
		return getInt("is_verified");
	}
	
	/**
	 * 是否绑定银行卡 注: 0、已绑定 1、未绑定
	 */
	public void setIsBank(java.lang.Integer isBank) {
		set("is_bank", isBank);
	}
	
	/**
	 * 是否绑定银行卡 注: 0、已绑定 1、未绑定
	 */
	public java.lang.Integer getIsBank() {
		return getInt("is_bank");
	}
	
	/**
	 * 是否绑定邮箱 注：0、已绑定 1、未绑定
	 */
	public void setEmailVerified(java.lang.Integer emailVerified) {
		set("email_verified", emailVerified);
	}
	
	/**
	 * 是否绑定邮箱 注：0、已绑定 1、未绑定
	 */
	public java.lang.Integer getEmailVerified() {
		return getInt("email_verified");
	}
	
	/**
	 * 是否绑定手机号 注：0、已绑定 1、未绑定
	 */
	public void setMobileVerified(java.lang.Integer mobileVerified) {
		set("mobile_verified", mobileVerified);
	}
	
	/**
	 * 是否绑定手机号 注：0、已绑定 1、未绑定
	 */
	public java.lang.Integer getMobileVerified() {
		return getInt("mobile_verified");
	}
	
	/**
	 * 是否绑定微信 注：0、已绑定1、未绑定
	 */
	public void setWeixinVerified(java.lang.Integer weixinVerified) {
		set("weixin_verified", weixinVerified);
	}
	
	/**
	 * 是否绑定微信 注：0、已绑定1、未绑定
	 */
	public java.lang.Integer getWeixinVerified() {
		return getInt("weixin_verified");
	}
	
	/**
	 * 用户名
	 */
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	/**
	 * 用户名
	 */
	public java.lang.String getUsername() {
		return getStr("username");
	}
	
	/**
	 * 用户账号 显示优先级：用户名>邮箱>手机号
	 */
	public void setAccountName(java.lang.String accountName) {
		set("account_name", accountName);
	}
	
	/**
	 * 用户账号 显示优先级：用户名>邮箱>手机号
	 */
	public java.lang.String getAccountName() {
		return getStr("account_name");
	}
	
	/**
	 * 手机号
	 */
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	/**
	 * 手机号
	 */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}
	
	/**
	 * 电子邮箱
	 */
	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	/**
	 * 电子邮箱
	 */
	public java.lang.String getEmail() {
		return getStr("email");
	}
	
	/**
	 * 用户类型 注：0、普通用户 1、企业用户 2、运营账号
	 */
	public void setUserType(java.lang.Integer userType) {
		set("user_type", userType);
	}
	
	/**
	 * 用户类型 注：0、普通用户 1、企业用户 2、运营账号
	 */
	public java.lang.Integer getUserType() {
		return getInt("user_type");
	}
	
	/**
	 * 密保手机号
	 */
	public void setPasswordMobile(java.lang.String passwordMobile) {
		set("password_mobile", passwordMobile);
	}
	
	/**
	 * 密保手机号
	 */
	public java.lang.String getPasswordMobile() {
		return getStr("password_mobile");
	}
	
	/**
	 * 微信号
	 */
	public void setWechat(java.lang.String wechat) {
		set("wechat", wechat);
	}
	
	/**
	 * 微信号
	 */
	public java.lang.String getWechat() {
		return getStr("wechat");
	}
	
	/**
	 * 每个微信号在平台对应的唯一编码
	 */
	public void setWechatId(java.lang.String wechatId) {
		set("wechat_id", wechatId);
	}
	
	/**
	 * 每个微信号在平台对应的唯一编码
	 */
	public java.lang.String getWechatId() {
		return getStr("wechat_id");
	}
	
	/**
	 * 注册时间
	 */
	public void setRegTime(java.util.Date regTime) {
		set("reg_time", regTime);
	}
	
	/**
	 * 注册时间
	 */
	public java.util.Date getRegTime() {
		return get("reg_time");
	}
	
	/**
	 * 最后一次登录时间
	 */
	public void setLastLoginTime(java.util.Date lastLoginTime) {
		set("last_login_time", lastLoginTime);
	}
	
	/**
	 * 最后一次登录时间
	 */
	public java.util.Date getLastLoginTime() {
		return get("last_login_time");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}
	
}
