package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOmApp<M extends BaseOmApp<M>> extends Model<M> implements IBean {

	/**
	 * 角色类型ID
	 */
	public void setAppId(java.lang.Long appId) {
		set("app_id", appId);
	}
	
	/**
	 * 角色类型ID
	 */
	public java.lang.Long getAppId() {
		return getLong("app_id");
	}
	
	/**
	 * LOGO路径
	 */
	public void setLogoUrl(java.lang.String logoUrl) {
		set("logo_url", logoUrl);
	}
	
	/**
	 * LOGO路径
	 */
	public java.lang.String getLogoUrl() {
		return getStr("logo_url");
	}
	
	/**
	 * 应用地址
	 */
	public void setAppUrl(java.lang.String appUrl) {
		set("app_url", appUrl);
	}
	
	/**
	 * 应用地址
	 */
	public java.lang.String getAppUrl() {
		return getStr("app_url");
	}
	
	/**
	 * 显示顺序
	 */
	public void setOrderNum(java.lang.Integer orderNum) {
		set("order_num", orderNum);
	}
	
	/**
	 * 显示顺序
	 */
	public java.lang.Integer getOrderNum() {
		return getInt("order_num");
	}
	
	/**
	 * 是否系统默认
	 */
	public void setIsDefault(java.lang.String isDefault) {
		set("is_default", isDefault);
	}
	
	/**
	 * 是否系统默认
	 */
	public java.lang.String getIsDefault() {
		return getStr("is_default");
	}
	
	/**
	 * 封面
	 */
	public void setCover(java.lang.String cover) {
		set("cover", cover);
	}
	
	/**
	 * 封面
	 */
	public java.lang.String getCover() {
		return getStr("cover");
	}
	
	/**
	 * 应用名称
	 */
	public void setAppName(java.lang.String appName) {
		set("app_name", appName);
	}
	
	/**
	 * 应用名称
	 */
	public java.lang.String getAppName() {
		return getStr("app_name");
	}
	
	/**
	 * 应用简称
	 */
	public void setAppShortName(java.lang.String appShortName) {
		set("app_short_name", appShortName);
	}
	
	/**
	 * 应用简称
	 */
	public java.lang.String getAppShortName() {
		return getStr("app_short_name");
	}
	
	/**
	 * 应用编码
	 */
	public void setAppCode(java.lang.String appCode) {
		set("app_code", appCode);
	}
	
	/**
	 * 应用编码
	 */
	public java.lang.String getAppCode() {
		return getStr("app_code");
	}
	
	/**
	 * 应用描述
	 */
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	/**
	 * 应用描述
	 */
	public java.lang.String getDescription() {
		return getStr("description");
	}
	
	/**
	 * 类型 1、企业中心等系统内置应用（类似系统的一个模块）  2、企业级应用
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 类型 1、企业中心等系统内置应用（类似系统的一个模块）  2、企业级应用
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}
	
}
