package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTmeAttachment<M extends BaseTmeAttachment<M>> extends Model<M> implements IBean {

	public void setFileId(java.lang.Long fileId) {
		set("file_id", fileId);
	}
	
	public java.lang.Long getFileId() {
		return getLong("file_id");
	}
	
	/**
	 * 组别编号
	 */
	public void setGroupCode(java.lang.String groupCode) {
		set("group_code", groupCode);
	}
	
	/**
	 * 组别编号
	 */
	public java.lang.String getGroupCode() {
		return getStr("group_code");
	}
	
	/**
	 * 文件名称
	 */
	public void setFileName(java.lang.String fileName) {
		set("file_name", fileName);
	}
	
	/**
	 * 文件名称
	 */
	public java.lang.String getFileName() {
		return getStr("file_name");
	}
	
	/**
	 * 文件保存地址
	 */
	public void setFileUrl(java.lang.String fileUrl) {
		set("file_url", fileUrl);
	}
	
	/**
	 * 文件保存地址
	 */
	public java.lang.String getFileUrl() {
		return getStr("file_url");
	}
	
	/**
	 * 文件格式后缀
	 */
	public void setFileType(java.lang.String fileType) {
		set("file_type", fileType);
	}
	
	/**
	 * 文件格式后缀
	 */
	public java.lang.String getFileType() {
		return getStr("file_type");
	}
	
	/**
	 * 文件大小
	 */
	public void setFileSize(java.lang.Long fileSize) {
		set("file_size", fileSize);
	}
	
	/**
	 * 文件大小
	 */
	public java.lang.Long getFileSize() {
		return getLong("file_size");
	}
	
	/**
	 * 文件随机名称
	 */
	public void setFileUuName(java.lang.String fileUuName) {
		set("file_uu_name", fileUuName);
	}
	
	/**
	 * 文件随机名称
	 */
	public java.lang.String getFileUuName() {
		return getStr("file_uu_name");
	}
	
	/**
	 * 是否删除 0=否 1=是
	 */
	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	/**
	 * 是否删除 0=否 1=是
	 */
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}
	
	/**
	 * 显示顺序 注：组内文件的顺序
	 */
	public void setOrderNum(java.lang.Integer orderNum) {
		set("order_num", orderNum);
	}
	
	/**
	 * 显示顺序 注：组内文件的顺序
	 */
	public java.lang.Integer getOrderNum() {
		return getInt("order_num");
	}
	
	/**
	 * 是否包含缩略图 0、否 1、是 注：只有图片存在缩略图
	 */
	public void setIsThumbnail(java.lang.Integer isThumbnail) {
		set("is_thumbnail", isThumbnail);
	}
	
	/**
	 * 是否包含缩略图 0、否 1、是 注：只有图片存在缩略图
	 */
	public java.lang.Integer getIsThumbnail() {
		return getInt("is_thumbnail");
	}
	
	/**
	 * 文件描述
	 */
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	/**
	 * 文件描述
	 */
	public java.lang.String getDescription() {
		return getStr("description");
	}
	
	/**
	 * 是否已完成状态上传的0、否1、是
	 */
	public void setIsFinish(java.lang.Integer isFinish) {
		set("is_finish", isFinish);
	}
	
	/**
	 * 是否已完成状态上传的0、否1、是
	 */
	public java.lang.Integer getIsFinish() {
		return getInt("is_finish");
	}
	
	/**
	 * 创建用户
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建用户
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	/**
	 * 修改用户
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 修改用户
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 修改时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}
	
}
