package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProject<M extends BaseProject<M>> extends Model<M> implements IBean {

	/**
	 * 项目id
	 */
	public void setProjId(java.lang.Long projId) {
		set("proj_id", projId);
	}
	
	/**
	 * 项目id
	 */
	public java.lang.Long getProjId() {
		return getLong("proj_id");
	}
	
	/**
	 * 项目名称
	 */
	public void setProjName(java.lang.String projName) {
		set("proj_name", projName);
	}
	
	/**
	 * 项目名称
	 */
	public java.lang.String getProjName() {
		return getStr("proj_name");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}
	
	/**
	 * 简称
	 */
	public void setShortName(java.lang.String shortName) {
		set("short_name", shortName);
	}
	
	/**
	 * 简称
	 */
	public java.lang.String getShortName() {
		return getStr("short_name");
	}
	
	/**
	 * 签约单位 注：中标单位
	 */
	public void setBiddingUnit(java.lang.String biddingUnit) {
		set("bidding_unit", biddingUnit);
	}
	
	/**
	 * 签约单位 注：中标单位
	 */
	public java.lang.String getBiddingUnit() {
		return getStr("bidding_unit");
	}
	
	/**
	 * 上级组织
	 */
	public void setSuperiorOrganization(java.lang.String superiorOrganization) {
		set("superior_organization", superiorOrganization);
	}
	
	/**
	 * 上级组织
	 */
	public java.lang.String getSuperiorOrganization() {
		return getStr("superior_organization");
	}
	
	/**
	 * 局指项目
	 */
	public void setAgencyProject(java.lang.String agencyProject) {
		set("agency_project", agencyProject);
	}
	
	/**
	 * 局指项目
	 */
	public java.lang.String getAgencyProject() {
		return getStr("agency_project");
	}
	
	/**
	 * 项目经理
	 */
	public void setManager(java.lang.String manager) {
		set("manager", manager);
	}
	
	/**
	 * 项目经理
	 */
	public java.lang.String getManager() {
		return getStr("manager");
	}
	
	/**
	 * 项目经理手机号
	 */
	public void setManagerMobile(java.lang.String managerMobile) {
		set("manager_mobile", managerMobile);
	}
	
	/**
	 * 项目经理手机号
	 */
	public java.lang.String getManagerMobile() {
		return getStr("manager_mobile");
	}
	
	/**
	 * 工程类别
	 */
	public void setConstructType(java.lang.String constructType) {
		set("construct_type", constructType);
	}
	
	/**
	 * 工程类别
	 */
	public java.lang.String getConstructType() {
		return getStr("construct_type");
	}
	
	/**
	 * 工程用途
	 */
	public void setConstructPurpose(java.lang.String constructPurpose) {
		set("construct_purpose", constructPurpose);
	}
	
	/**
	 * 工程用途
	 */
	public java.lang.String getConstructPurpose() {
		return getStr("construct_purpose");
	}
	
	/**
	 * 工程造价
	 */
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	/**
	 * 工程造价
	 */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}
	
	/**
	 * 建筑面积
	 */
	public void setArea(java.math.BigDecimal area) {
		set("area", area);
	}
	
	/**
	 * 建筑面积
	 */
	public java.math.BigDecimal getArea() {
		return get("area");
	}
	
	/**
	 * 工程状态
	 */
	public void setConstructStatus(java.lang.String constructStatus) {
		set("construct_status", constructStatus);
	}
	
	/**
	 * 工程状态
	 */
	public java.lang.String getConstructStatus() {
		return getStr("construct_status");
	}
	
	/**
	 * 结构类型
	 */
	public void setStructType(java.lang.String structType) {
		set("struct_type", structType);
	}
	
	/**
	 * 结构类型
	 */
	public java.lang.String getStructType() {
		return getStr("struct_type");
	}
	
	/**
	 * 工程地点
	 */
	public void setLocation(java.lang.String location) {
		set("location", location);
	}
	
	/**
	 * 工程地点
	 */
	public java.lang.String getLocation() {
		return getStr("location");
	}
	
	/**
	 * 计划开工日期
	 */
	public void setPlanStart(java.util.Date planStart) {
		set("plan_start", planStart);
	}
	
	/**
	 * 计划开工日期
	 */
	public java.util.Date getPlanStart() {
		return get("plan_start");
	}
	
	/**
	 * 计划竣工日期
	 */
	public void setPlanEnd(java.util.Date planEnd) {
		set("plan_end", planEnd);
	}
	
	/**
	 * 计划竣工日期
	 */
	public java.util.Date getPlanEnd() {
		return get("plan_end");
	}
	
	/**
	 * 实际开工日期
	 */
	public void setActualStart(java.util.Date actualStart) {
		set("actual_start", actualStart);
	}
	
	/**
	 * 实际开工日期
	 */
	public java.util.Date getActualStart() {
		return get("actual_start");
	}
	
	/**
	 * 设计单位
	 */
	public void setDesignUnit(java.lang.String designUnit) {
		set("design_unit", designUnit);
	}
	
	/**
	 * 设计单位
	 */
	public java.lang.String getDesignUnit() {
		return getStr("design_unit");
	}
	
	/**
	 * 建设单位
	 */
	public void setConstructUnit(java.lang.String constructUnit) {
		set("construct_unit", constructUnit);
	}
	
	/**
	 * 建设单位
	 */
	public java.lang.String getConstructUnit() {
		return getStr("construct_unit");
	}
	
	/**
	 * 业主单位
	 */
	public void setOwnerCompany(java.lang.String ownerCompany) {
		set("owner_company", ownerCompany);
	}
	
	/**
	 * 业主单位
	 */
	public java.lang.String getOwnerCompany() {
		return getStr("owner_company");
	}
	
	/**
	 * 监理单位
	 */
	public void setSupervisingUnit(java.lang.String supervisingUnit) {
		set("supervising_unit", supervisingUnit);
	}
	
	/**
	 * 监理单位
	 */
	public java.lang.String getSupervisingUnit() {
		return getStr("supervising_unit");
	}
	
	/**
	 * 工程概况
	 */
	public void setOverview(java.lang.String overview) {
		set("overview", overview);
	}
	
	/**
	 * 工程概况
	 */
	public java.lang.String getOverview() {
		return getStr("overview");
	}
	
	/**
	 * 同步编码
	 */
	public void setSyncCode(java.lang.String syncCode) {
		set("sync_code", syncCode);
	}
	
	/**
	 * 同步编码
	 */
	public java.lang.String getSyncCode() {
		return getStr("sync_code");
	}
	
	/**
	 * 广联达数字项目管理平台ID
	 */
	public void setXmglId(java.lang.Long xmglId) {
		set("xmgl_id", xmglId);
	}
	
	/**
	 * 广联达数字项目管理平台ID
	 */
	public java.lang.Long getXmglId() {
		return getLong("xmgl_id");
	}
	
	/**
	 * 组织ID
	 */
	public void setOrgId(java.lang.Long orgId) {
		set("org_id", orgId);
	}
	
	/**
	 * 组织ID
	 */
	public java.lang.Long getOrgId() {
		return getLong("org_id");
	}
	
	/**
	 * 经度
	 */
	public void setLongitude(java.math.BigDecimal longitude) {
		set("longitude", longitude);
	}
	
	/**
	 * 经度
	 */
	public java.math.BigDecimal getLongitude() {
		return get("longitude");
	}
	
	/**
	 * 纬度
	 */
	public void setLatitude(java.math.BigDecimal latitude) {
		set("latitude", latitude);
	}
	
	/**
	 * 纬度
	 */
	public java.math.BigDecimal getLatitude() {
		return get("latitude");
	}
	
	/**
	 * 租户ID
	 */
	public void setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
	}
	
	/**
	 * 租户ID
	 */
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}
	
	/**
	 * 合同签订日期
	 */
	public void setContractDate(java.util.Date contractDate) {
		set("contract_date", contractDate);
	}
	
	/**
	 * 合同签订日期
	 */
	public java.util.Date getContractDate() {
		return get("contract_date");
	}
	
	/**
	 * 实际竣工日期
	 */
	public void setRealFinishDate(java.util.Date realFinishDate) {
		set("real_finish_date", realFinishDate);
	}
	
	/**
	 * 实际竣工日期
	 */
	public java.util.Date getRealFinishDate() {
		return get("real_finish_date");
	}
	
	/**
	 * 是否删除，0：正常，1：假删除
	 */
	public void setDeleted(java.lang.String deleted) {
		set("deleted", deleted);
	}
	
	/**
	 * 是否删除，0：正常，1：假删除
	 */
	public java.lang.String getDeleted() {
		return getStr("deleted");
	}
	
	/**
	 * 组织类型
	 */
	public void setOrgType(java.lang.String orgType) {
		set("org_type", orgType);
	}
	
	/**
	 * 组织类型
	 */
	public java.lang.String getOrgType() {
		return getStr("org_type");
	}
	
	/**
	 * 组织全ID 如 1/2/3
	 */
	public void setFullId(java.lang.String fullId) {
		set("full_id", fullId);
	}
	
	/**
	 * 组织全ID 如 1/2/3
	 */
	public java.lang.String getFullId() {
		return getStr("full_id");
	}
	
	/**
	 * 同步时间
	 */
	public void setSyncTime(java.util.Date syncTime) {
		set("sync_time", syncTime);
	}
	
	/**
	 * 同步时间
	 */
	public java.util.Date getSyncTime() {
		return get("sync_time");
	}
	
	/**
	 * 项目编号
	 */
	public void setProjectCode(java.lang.String projectCode) {
		set("project_code", projectCode);
	}
	
	/**
	 * 项目编号
	 */
	public java.lang.String getProjectCode() {
		return getStr("project_code");
	}
	
	/**
	 * 局指项目
	 */
	public void setCommandName(java.lang.String commandName) {
		set("command_name", commandName);
	}
	
	/**
	 * 局指项目
	 */
	public java.lang.String getCommandName() {
		return getStr("command_name");
	}
	
	/**
	 * 编码
	 */
	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	/**
	 * 编码
	 */
	public java.lang.String getCode() {
		return getStr("code");
	}
	
	/**
	 * 父组织ID
	 */
	public void setParentOrgId(java.lang.Long parentOrgId) {
		set("parent_org_id", parentOrgId);
	}
	
	/**
	 * 父组织ID
	 */
	public java.lang.Long getParentOrgId() {
		return getLong("parent_org_id");
	}
	
}
