package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTmpProcessType<M extends BaseTmpProcessType<M>> extends Model<M> implements IBean {

	/**
	 * 工序分类ID
	 */
	public void setTypeId(java.lang.Long typeId) {
		set("type_id", typeId);
	}
	
	/**
	 * 工序分类ID
	 */
	public java.lang.Long getTypeId() {
		return getLong("type_id");
	}
	
	/**
	 * 父工序分类ID
	 */
	public void setParentId(java.lang.Long parentId) {
		set("parent_id", parentId);
	}
	
	/**
	 * 父工序分类ID
	 */
	public java.lang.Long getParentId() {
		return getLong("parent_id");
	}
	
	/**
	 * 企业工序分类ID
	 */
	public void setEntTypeId(java.lang.Long entTypeId) {
		set("ent_type_id", entTypeId);
	}
	
	/**
	 * 企业工序分类ID
	 */
	public java.lang.Long getEntTypeId() {
		return getLong("ent_type_id");
	}
	
	/**
	 * 企业ID
	 */
	public void setEntId(java.lang.Long entId) {
		set("ent_id", entId);
	}
	
	/**
	 * 企业ID
	 */
	public java.lang.Long getEntId() {
		return getLong("ent_id");
	}
	
	/**
	 * 项目ID
	 */
	public void setProjId(java.lang.Long projId) {
		set("proj_id", projId);
	}
	
	/**
	 * 项目ID
	 */
	public java.lang.Long getProjId() {
		return getLong("proj_id");
	}
	
	/**
	 * 分类名称
	 */
	public void setTypeName(java.lang.String typeName) {
		set("type_name", typeName);
	}
	
	/**
	 * 分类名称
	 */
	public java.lang.String getTypeName() {
		return getStr("type_name");
	}
	
	/**
	 * 分类编号
	 */
	public void setNumber(java.lang.String number) {
		set("number", number);
	}
	
	/**
	 * 分类编号
	 */
	public java.lang.String getNumber() {
		return getStr("number");
	}
	
	/**
	 * 祖级列表
	 */
	public void setAncestors(java.lang.String ancestors) {
		set("ancestors", ancestors);
	}
	
	/**
	 * 祖级列表
	 */
	public java.lang.String getAncestors() {
		return getStr("ancestors");
	}
	
	/**
	 * 显示顺序
	 */
	public void setOrderNum(java.lang.Integer orderNum) {
		set("order_num", orderNum);
	}
	
	/**
	 * 显示顺序
	 */
	public java.lang.Integer getOrderNum() {
		return getInt("order_num");
	}
	
	/**
	 * 分类级别
	 */
	public void setTypeLevel(java.lang.Integer typeLevel) {
		set("type_level", typeLevel);
	}
	
	/**
	 * 分类级别
	 */
	public java.lang.Integer getTypeLevel() {
		return getInt("type_level");
	}
	
	/**
	 * 是否删除 0、否 1、是
	 */
	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	/**
	 * 是否删除 0、否 1、是
	 */
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setOldId(java.lang.String oldId) {
		set("old_id", oldId);
	}

	public java.lang.String getOldId() {
		return getStr("old_id");
	}
	
}
