package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTmpProcessTask<M extends BaseTmpProcessTask<M>> extends Model<M> implements IBean {

	/**
	 * 工序ID
	 */
	public void setPrcId(java.lang.Long prcId) {
		set("prc_id", prcId);
	}
	
	/**
	 * 工序ID
	 */
	public java.lang.Long getPrcId() {
		return getLong("prc_id");
	}
	
	/**
	 * 任务标准ID
	 */
	public void setTaskId(java.lang.Long taskId) {
		set("task_id", taskId);
	}
	
	/**
	 * 任务标准ID
	 */
	public java.lang.Long getTaskId() {
		return getLong("task_id");
	}
	
	/**
	 * 显示顺序
	 */
	public void setOrderNum(java.lang.Integer orderNum) {
		set("order_num", orderNum);
	}
	
	/**
	 * 显示顺序
	 */
	public java.lang.Integer getOrderNum() {
		return getInt("order_num");
	}
	
	/**
	 * 前置任务
	 */
	public void setPreposeTask(java.lang.String preposeTask) {
		set("prepose_task", preposeTask);
	}
	
	/**
	 * 前置任务
	 */
	public java.lang.String getPreposeTask() {
		return getStr("prepose_task");
	}
	
}
