package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTmeTaskStandardType<M extends BaseTmeTaskStandardType<M>> extends Model<M> implements IBean {

	public void setTypeId(java.lang.Long typeId) {
		set("type_id", typeId);
	}
	
	public java.lang.Long getTypeId() {
		return getLong("type_id");
	}
	
	public void setParentId(java.lang.Long parentId) {
		set("parent_id", parentId);
	}
	
	public java.lang.Long getParentId() {
		return getLong("parent_id");
	}
	
	public void setEntId(java.lang.Long entId) {
		set("ent_id", entId);
	}
	
	public java.lang.Long getEntId() {
		return getLong("ent_id");
	}
	
	public void setTypeName(java.lang.String typeName) {
		set("type_name", typeName);
	}
	
	public java.lang.String getTypeName() {
		return getStr("type_name");
	}
	
	public void setNumber(java.lang.String number) {
		set("number", number);
	}
	
	public java.lang.String getNumber() {
		return getStr("number");
	}
	
	public void setAncestors(java.lang.String ancestors) {
		set("ancestors", ancestors);
	}
	
	public java.lang.String getAncestors() {
		return getStr("ancestors");
	}
	
	public void setOrderNum(java.lang.Integer orderNum) {
		set("order_num", orderNum);
	}
	
	public java.lang.Integer getOrderNum() {
		return getInt("order_num");
	}
	
	public void setTypeLevel(java.lang.Integer typeLevel) {
		set("type_level", typeLevel);
	}
	
	public java.lang.Integer getTypeLevel() {
		return getInt("type_level");
	}
	
	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}
	
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}
	
}
