package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProjectLog<M extends BaseProjectLog<M>> extends Model<M> implements IBean {

	/**
	 * 项目id
	 */
	public void setProjId(java.lang.Long projId) {
		set("proj_id", projId);
	}
	
	/**
	 * 项目id
	 */
	public java.lang.Long getProjId() {
		return getLong("proj_id");
	}
	
	/**
	 * 项目名称
	 */
	public void setProjName(java.lang.String projName) {
		set("proj_name", projName);
	}
	
	/**
	 * 项目名称
	 */
	public java.lang.String getProjName() {
		return getStr("proj_name");
	}
	
	/**
	 * 项目地址
	 */
	public void setProjAddress(java.lang.String projAddress) {
		set("proj_address", projAddress);
	}
	
	/**
	 * 项目地址
	 */
	public java.lang.String getProjAddress() {
		return getStr("proj_address");
	}
	
	/**
	 * 项目状态 注：平台字典
	 */
	public void setProjStatus(java.lang.Integer projStatus) {
		set("proj_status", projStatus);
	}
	
	/**
	 * 项目状态 注：平台字典
	 */
	public java.lang.Integer getProjStatus() {
		return getInt("proj_status");
	}
	
	/**
	 * 加入时间或参建时间
	 */
	public void setJoinTime(java.util.Date joinTime) {
		set("join_time", joinTime);
	}
	
	/**
	 * 加入时间或参建时间
	 */
	public java.util.Date getJoinTime() {
		return get("join_time");
	}
	
	/**
	 * 退出时间
	 */
	public void setQuitTime(java.util.Date quitTime) {
		set("quit_time", quitTime);
	}
	
	/**
	 * 退出时间
	 */
	public java.util.Date getQuitTime() {
		return get("quit_time");
	}
	
	/**
	 * 参加项目天数或参与项目周期
	 */
	public void setJoinDay(java.lang.Integer joinDay) {
		set("join_day", joinDay);
	}
	
	/**
	 * 参加项目天数或参与项目周期
	 */
	public java.lang.Integer getJoinDay() {
		return getInt("join_day");
	}
	
	/**
	 * 项目评价
	 */
	public void setProjAppraise(java.lang.String projAppraise) {
		set("proj_appraise", projAppraise);
	}
	
	/**
	 * 项目评价
	 */
	public java.lang.String getProjAppraise() {
		return getStr("proj_appraise");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}
	
}
