package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUserWork<M extends BaseSysUserWork<M>> extends Model<M> implements IBean {

	/**
	 * 用户工作教育ID
	 */
	public void setWorkId(java.lang.Long workId) {
		set("work_id", workId);
	}
	
	/**
	 * 用户工作教育ID
	 */
	public java.lang.Long getWorkId() {
		return getLong("work_id");
	}
	
	/**
	 * 用户ID
	 */
	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户ID
	 */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}
	
	/**
	 * 人员类别 注：平台字典（管理人员、技术工人）
	 */
	public void setPeopleType(java.lang.Integer peopleType) {
		set("people_type", peopleType);
	}
	
	/**
	 * 人员类别 注：平台字典（管理人员、技术工人）
	 */
	public java.lang.Integer getPeopleType() {
		return getInt("people_type");
	}
	
	/**
	 * 最高学历 注：平台字典
	 */
	public void setHighestEducation(java.lang.Integer highestEducation) {
		set("highest_education", highestEducation);
	}
	
	/**
	 * 最高学历 注：平台字典
	 */
	public java.lang.Integer getHighestEducation() {
		return getInt("highest_education");
	}
	
	/**
	 * 专业 注：平台字典
	 */
	public void setProfession(java.lang.Integer profession) {
		set("profession", profession);
	}
	
	/**
	 * 专业 注：平台字典
	 */
	public java.lang.Integer getProfession() {
		return getInt("profession");
	}
	
	/**
	 * 职称级别 注：平台字典
	 */
	public void setTitleLevel(java.lang.Integer titleLevel) {
		set("title_level", titleLevel);
	}
	
	/**
	 * 职称级别 注：平台字典
	 */
	public java.lang.Integer getTitleLevel() {
		return getInt("title_level");
	}
	
	/**
	 * 职称专业 注：平台字典
	 */
	public void setTitleProfession(java.lang.Integer titleProfession) {
		set("title_profession", titleProfession);
	}
	
	/**
	 * 职称专业 注：平台字典
	 */
	public java.lang.Integer getTitleProfession() {
		return getInt("title_profession");
	}
	
	/**
	 * 工种 注：平台字典
	 */
	public void setWorkType(java.lang.Integer workType) {
		set("work_type", workType);
	}
	
	/**
	 * 工种 注：平台字典
	 */
	public java.lang.Integer getWorkType() {
		return getInt("work_type");
	}
	
	/**
	 * 工作所在地 注：平台字典 备注：前期自由编辑，后期调用接口或者平台字典
	 */
	public void setWorkAddress(java.lang.String workAddress) {
		set("work_address", workAddress);
	}
	
	/**
	 * 工作所在地 注：平台字典 备注：前期自由编辑，后期调用接口或者平台字典
	 */
	public java.lang.String getWorkAddress() {
		return getStr("work_address");
	}
	
}
