package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUserLog<M extends BaseSysUserLog<M>> extends Model<M> implements IBean {

	/**
	 * 用户日志ID
	 */
	public void setLogId(java.lang.Long logId) {
		set("log_id", logId);
	}
	
	/**
	 * 用户日志ID
	 */
	public java.lang.Long getLogId() {
		return getLong("log_id");
	}
	
	/**
	 * 用户ID
	 */
	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户ID
	 */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}
	
	/**
	 * 操作类型 1、注册2、认证成功3、认证失败4、锁定5、解锁6、加入黑名单7、解除黑名单
	 */
	public void setOperType(java.lang.Integer operType) {
		set("oper_type", operType);
	}
	
	/**
	 * 操作类型 1、注册2、认证成功3、认证失败4、锁定5、解锁6、加入黑名单7、解除黑名单
	 */
	public java.lang.Integer getOperType() {
		return getInt("oper_type");
	}
	
	/**
	 * 原因
	 */
	public void setCause(java.lang.String cause) {
		set("cause", cause);
	}
	
	/**
	 * 原因
	 */
	public java.lang.String getCause() {
		return getStr("cause");
	}
	
	/**
	 * 操作者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 操作者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 操作时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 操作时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
}
