package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJobLog<M extends BaseJobLog<M>> extends Model<M> implements IBean {

	/**
	 * 从业记录id
	 */
	public void setJobId(java.lang.Long jobId) {
		set("job_id", jobId);
	}
	
	/**
	 * 从业记录id
	 */
	public java.lang.Long getJobId() {
		return getLong("job_id");
	}
	
	/**
	 * 用户id
	 */
	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}
	
	/**
	 * 工号
	 */
	public void setJobNumber(java.lang.String jobNumber) {
		set("job_number", jobNumber);
	}
	
	/**
	 * 工号
	 */
	public java.lang.String getJobNumber() {
		return getStr("job_number");
	}
	
	/**
	 * 职务
	 */
	public void setPosition(java.lang.String position) {
		set("position", position);
	}
	
	/**
	 * 职务
	 */
	public java.lang.String getPosition() {
		return getStr("position");
	}
	
	/**
	 * 工作性质 注：1、全职 2、兼职
	 */
	public void setWorkProperty(java.lang.String workProperty) {
		set("work_property", workProperty);
	}
	
	/**
	 * 工作性质 注：1、全职 2、兼职
	 */
	public java.lang.String getWorkProperty() {
		return getStr("work_property");
	}
	
	/**
	 * 加入时间
	 */
	public void setJoinTime(java.util.Date joinTime) {
		set("join_time", joinTime);
	}
	
	/**
	 * 加入时间
	 */
	public java.util.Date getJoinTime() {
		return get("join_time");
	}
	
	/**
	 * 离职时间
	 */
	public void setQuitTime(java.util.Date quitTime) {
		set("quit_time", quitTime);
	}
	
	/**
	 * 离职时间
	 */
	public java.util.Date getQuitTime() {
		return get("quit_time");
	}
	
	/**
	 * 离职原因
	 */
	public void setQuitCause(java.lang.String quitCause) {
		set("quit_cause", quitCause);
	}
	
	/**
	 * 离职原因
	 */
	public java.lang.String getQuitCause() {
		return getStr("quit_cause");
	}
	
	/**
	 * 在职天数
	 */
	public void setJoinDay(java.lang.Integer joinDay) {
		set("join_day", joinDay);
	}
	
	/**
	 * 在职天数
	 */
	public java.lang.Integer getJoinDay() {
		return getInt("join_day");
	}
	
	/**
	 * 所从事岗位
	 */
	public void setCompanyPost(java.lang.String companyPost) {
		set("company_post", companyPost);
	}
	
	/**
	 * 所从事岗位
	 */
	public java.lang.String getCompanyPost() {
		return getStr("company_post");
	}
	
	/**
	 * 所属部门/班组  注：后期要改为组织机构ID
	 */
	public void setDeptId(java.lang.Long deptId) {
		set("dept_id", deptId);
	}
	
	/**
	 * 所属部门/班组  注：后期要改为组织机构ID
	 */
	public java.lang.Long getDeptId() {
		return getLong("dept_id");
	}
	
	/**
	 * 所属企业ID
	 */
	public void setEntId(java.lang.Long entId) {
		set("ent_id", entId);
	}
	
	/**
	 * 所属企业ID
	 */
	public java.lang.Long getEntId() {
		return getLong("ent_id");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}
	
}
