package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTmpTaskStandard<M extends BaseTmpTaskStandard<M>> extends Model<M> implements IBean {

	/**
	 * 任务标准ID
	 */
	public void setTaskId(java.lang.Long taskId) {
		set("task_id", taskId);
	}
	
	/**
	 * 任务标准ID
	 */
	public java.lang.Long getTaskId() {
		return getLong("task_id");
	}
	
	/**
	 * 项目ID
	 */
	public void setProjId(java.lang.Long projId) {
		set("proj_id", projId);
	}
	
	/**
	 * 项目ID
	 */
	public java.lang.Long getProjId() {
		return getLong("proj_id");
	}
	
	/**
	 * 企业ID
	 */
	public void setEntId(java.lang.Long entId) {
		set("ent_id", entId);
	}
	
	/**
	 * 企业ID
	 */
	public java.lang.Long getEntId() {
		return getLong("ent_id");
	}
	
	/**
	 * 对应的企业任务标准ID
	 */
	public void setEntTaskId(java.lang.Long entTaskId) {
		set("ent_task_id", entTaskId);
	}
	
	/**
	 * 对应的企业任务标准ID
	 */
	public java.lang.Long getEntTaskId() {
		return getLong("ent_task_id");
	}
	
	/**
	 * 任务标准分类ID
	 */
	public void setTypeId(java.lang.Long typeId) {
		set("type_id", typeId);
	}
	
	/**
	 * 任务标准分类ID
	 */
	public java.lang.Long getTypeId() {
		return getLong("type_id");
	}
	
	/**
	 * 审批流程ID 注：审批模板
	 */
	public void setFlowId(java.lang.Long flowId) {
		set("flow_id", flowId);
	}
	
	/**
	 * 审批流程ID 注：审批模板
	 */
	public java.lang.Long getFlowId() {
		return getLong("flow_id");
	}
	
	/**
	 * 任务标准名称
	 */
	public void setTaskName(java.lang.String taskName) {
		set("task_name", taskName);
	}
	
	/**
	 * 任务标准名称
	 */
	public java.lang.String getTaskName() {
		return getStr("task_name");
	}
	
	/**
	 * 工法专业 注：业务字典-工法业务字典
	 */
	public void setProfession(java.lang.String profession) {
		set("profession", profession);
	}
	
	/**
	 * 工法专业 注：业务字典-工法业务字典
	 */
	public java.lang.String getProfession() {
		return getStr("profession");
	}
	
	/**
	 * 状态 1、 草稿（未提交的标准。）2、修改中（对已完成的标准修改后保存未提交）3、审批中（修改后提交）4、待审批（当前待审批人为当前账号）5、已驳回（审批完成并驳回）6、已完成（审批完成并同意）
	 */
	public void setState(java.lang.String state) {
		set("state", state);
	}
	
	/**
	 * 状态 1、 草稿（未提交的标准。）2、修改中（对已完成的标准修改后保存未提交）3、审批中（修改后提交）4、待审批（当前待审批人为当前账号）5、已驳回（审批完成并驳回）6、已完成（审批完成并同意）
	 */
	public java.lang.String getState() {
		return getStr("state");
	}
	
	/**
	 * 附件组ID 注：与upload_file表group_code字段关联
	 */
	public void setAttachment(java.lang.String attachment) {
		set("attachment", attachment);
	}
	
	/**
	 * 附件组ID 注：与upload_file表group_code字段关联
	 */
	public java.lang.String getAttachment() {
		return getStr("attachment");
	}
	
	/**
	 * 发文编号
	 */
	public void setIssueNo(java.lang.String issueNo) {
		set("issue_no", issueNo);
	}
	
	/**
	 * 发文编号
	 */
	public java.lang.String getIssueNo() {
		return getStr("issue_no");
	}
	
	/**
	 * 审批文号
	 */
	public void setApprovalNo(java.lang.String approvalNo) {
		set("approval_no", approvalNo);
	}
	
	/**
	 * 审批文号
	 */
	public java.lang.String getApprovalNo() {
		return getStr("approval_no");
	}
	
	/**
	 * 工种 注：数据来自项目平台
	 */
	public void setWorkType(java.lang.String workType) {
		set("work_type", workType);
	}
	
	/**
	 * 工种 注：数据来自项目平台
	 */
	public java.lang.String getWorkType() {
		return getStr("work_type");
	}
	
	/**
	 * 检查人
	 */
	public void setCheckMan(java.lang.String checkMan) {
		set("check_man", checkMan);
	}
	
	/**
	 * 检查人
	 */
	public java.lang.String getCheckMan() {
		return getStr("check_man");
	}
	
	/**
	 * 任务类型 1、企业标准 2、项目新增3、项目优化
	 */
	public void setTaskType(java.lang.String taskType) {
		set("task_type", taskType);
	}
	
	/**
	 * 任务类型 1、企业标准 2、项目新增3、项目优化
	 */
	public java.lang.String getTaskType() {
		return getStr("task_type");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	/**
	 * 反馈结果  1、已上报  2、已驳回  3、已接受
	 */
	public void setFeedback(java.lang.String feedback) {
		set("feedback", feedback);
	}
	
	/**
	 * 反馈结果  1、已上报  2、已驳回  3、已接受
	 */
	public java.lang.String getFeedback() {
		return getStr("feedback");
	}
	
	/**
	 * 是否删除 0、否 1、是
	 */
	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	/**
	 * 是否删除 0、否 1、是
	 */
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}
	
}
