package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUserDept<M extends BaseSysUserDept<M>> extends Model<M> implements IBean {

	/**
	 * 用户ID
	 */
	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户ID
	 */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}
	
	/**
	 * 部门ID
	 */
	public void setDeptId(java.lang.Long deptId) {
		set("dept_id", deptId);
	}
	
	/**
	 * 部门ID
	 */
	public java.lang.Long getDeptId() {
		return getLong("dept_id");
	}
	
	/**
	 * 从业记录ID
	 */
	public void setJobLogId(java.lang.Long jobLogId) {
		set("job_log_id", jobLogId);
	}
	
	/**
	 * 从业记录ID
	 */
	public java.lang.Long getJobLogId() {
		return getLong("job_log_id");
	}
	
	/**
	 * 加入时间
	 */
	public void setJoinTime(java.util.Date joinTime) {
		set("join_time", joinTime);
	}
	
	/**
	 * 加入时间
	 */
	public java.util.Date getJoinTime() {
		return get("join_time");
	}
	
	/**
	 * 工作性质 注：1、全职 2、兼职
	 */
	public void setWorkProperty(java.lang.String workProperty) {
		set("work_property", workProperty);
	}
	
	/**
	 * 工作性质 注：1、全职 2、兼职
	 */
	public java.lang.String getWorkProperty() {
		return getStr("work_property");
	}
	
	/**
	 * 职务
	 */
	public void setPosition(java.lang.String position) {
		set("position", position);
	}
	
	/**
	 * 职务
	 */
	public java.lang.String getPosition() {
		return getStr("position");
	}
	
	/**
	 * 是否企业管理员
	 */
	public void setEntAdministrator(java.lang.String entAdministrator) {
		set("ent_administrator", entAdministrator);
	}
	
	/**
	 * 是否企业管理员
	 */
	public java.lang.String getEntAdministrator() {
		return getStr("ent_administrator");
	}
	
}
