package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTmeTaskStandard<M extends BaseTmeTaskStandard<M>> extends Model<M> implements IBean {

	/**
	 * 任务标准ID
	 */
	public void setTaskId(java.lang.Long taskId) {
		set("task_id", taskId);
	}
	
	/**
	 * 任务标准ID
	 */
	public java.lang.Long getTaskId() {
		return getLong("task_id");
	}
	
	/**
	 * 企业ID
	 */
	public void setEntId(java.lang.Long entId) {
		set("ent_id", entId);
	}
	
	/**
	 * 企业ID
	 */
	public java.lang.Long getEntId() {
		return getLong("ent_id");
	}
	
	/**
	 * 任务标准分类ID
	 */
	public void setTypeId(java.lang.Long typeId) {
		set("type_id", typeId);
	}
	
	/**
	 * 任务标准分类ID
	 */
	public java.lang.Long getTypeId() {
		return getLong("type_id");
	}
	
	/**
	 * 审批流程ID 注：审批模板
	 */
	public void setFlowId(java.lang.Long flowId) {
		set("flow_id", flowId);
	}
	
	/**
	 * 审批流程ID 注：审批模板
	 */
	public java.lang.Long getFlowId() {
		return getLong("flow_id");
	}
	
	/**
	 * 任务标准名称
	 */
	public void setTaskName(java.lang.String taskName) {
		set("task_name", taskName);
	}
	
	/**
	 * 任务标准名称
	 */
	public java.lang.String getTaskName() {
		return getStr("task_name");
	}
	
	/**
	 * 工法专业 注：业务字典-工法业务字典
	 */
	public void setProfession(java.lang.String profession) {
		set("profession", profession);
	}
	
	/**
	 * 工法专业 注：业务字典-工法业务字典
	 */
	public java.lang.String getProfession() {
		return getStr("profession");
	}
	
	/**
	 * 状态 1、 草稿（未提交的标准。）2、修改中（对已完成的标准修改后保存未提交）3、审批中（修改后提交）4、待审批（当前待审批人为当前账号）5、已驳回（审批完成并驳回）6、已完成（审批完成并同意）
	 */
	public void setState(java.lang.String state) {
		set("state", state);
	}
	
	/**
	 * 状态 1、 草稿（未提交的标准。）2、修改中（对已完成的标准修改后保存未提交）3、审批中（修改后提交）4、待审批（当前待审批人为当前账号）5、已驳回（审批完成并驳回）6、已完成（审批完成并同意）
	 */
	public java.lang.String getState() {
		return getStr("state");
	}
	
	/**
	 * 附件组ID 注：与upload_file表group_code字段关联
	 */
	public void setAttachment(java.lang.String attachment) {
		set("attachment", attachment);
	}
	
	/**
	 * 附件组ID 注：与upload_file表group_code字段关联
	 */
	public java.lang.String getAttachment() {
		return getStr("attachment");
	}
	
	/**
	 * 发文编号
	 */
	public void setIssueNo(java.lang.String issueNo) {
		set("issue_no", issueNo);
	}
	
	/**
	 * 发文编号
	 */
	public java.lang.String getIssueNo() {
		return getStr("issue_no");
	}
	
	/**
	 * 审批文号
	 */
	public void setApprovalNo(java.lang.String approvalNo) {
		set("approval_no", approvalNo);
	}
	
	/**
	 * 审批文号
	 */
	public java.lang.String getApprovalNo() {
		return getStr("approval_no");
	}
	
	/**
	 * 工种   注：数据来自项目平台
	 */
	public void setWorkType(java.lang.String workType) {
		set("work_type", workType);
	}
	
	/**
	 * 工种   注：数据来自项目平台
	 */
	public java.lang.String getWorkType() {
		return getStr("work_type");
	}
	
	/**
	 * 工种   注：输入的值
	 */
	public void setWorkTypeStr(java.lang.String workTypeStr) {
		set("work_type_str", workTypeStr);
	}
	
	/**
	 * 工种   注：输入的值
	 */
	public java.lang.String getWorkTypeStr() {
		return getStr("work_type_str");
	}
	
	/**
	 * 检查人
	 */
	public void setCheckMan(java.lang.String checkMan) {
		set("check_man", checkMan);
	}
	
	/**
	 * 检查人
	 */
	public java.lang.String getCheckMan() {
		return getStr("check_man");
	}
	
	/**
	 * 检查人 注：输入的值
	 */
	public void setCheckManStr(java.lang.String checkManStr) {
		set("check_man_str", checkManStr);
	}
	
	/**
	 * 检查人 注：输入的值
	 */
	public java.lang.String getCheckManStr() {
		return getStr("check_man_str");
	}
	
	/**
	 * 是否删除 0、否 1、是
	 */
	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	/**
	 * 是否删除 0、否 1、是
	 */
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}
	
	/**
	 * 创建人ID
	 */
	public void setCreateById(java.lang.Long createById) {
		set("create_by_id", createById);
	}
	
	/**
	 * 创建人ID
	 */
	public java.lang.Long getCreateById() {
		return getLong("create_by_id");
	}
	
	/**
	 * 修改人ID
	 */
	public void setUpdateById(java.lang.Long updateById) {
		set("update_by_id", updateById);
	}
	
	/**
	 * 修改人ID
	 */
	public java.lang.Long getUpdateById() {
		return getLong("update_by_id");
	}
	
	/**
	 * 初始化ID 注：每条任务标准，所有版本得初始化ID一样
	 */
	public void setInitId(java.lang.Long initId) {
		set("init_id", initId);
	}
	
	/**
	 * 初始化ID 注：每条任务标准，所有版本得初始化ID一样
	 */
	public java.lang.Long getInitId() {
		return getLong("init_id");
	}
	
	/**
	 * 任务标准版本号
	 */
	public void setTaskVersion(java.lang.String taskVersion) {
		set("task_version", taskVersion);
	}
	
	/**
	 * 任务标准版本号
	 */
	public java.lang.String getTaskVersion() {
		return getStr("task_version");
	}
	
	/**
	 * 显示顺序
	 */
	public void setOrderNum(java.lang.Integer orderNum) {
		set("order_num", orderNum);
	}
	
	/**
	 * 显示顺序
	 */
	public java.lang.Integer getOrderNum() {
		return getInt("order_num");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}
	
}
