package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUserDetail<M extends BaseSysUserDetail<M>> extends Model<M> implements IBean {

	/**
	 * 用户详情ID
	 */
	public void setDetailId(java.lang.Long detailId) {
		set("detail_id", detailId);
	}
	
	/**
	 * 用户详情ID
	 */
	public java.lang.Long getDetailId() {
		return getLong("detail_id");
	}
	
	/**
	 * 用户ID
	 */
	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户ID
	 */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}
	
	/**
	 * 用户性别 注：0、男 1、女
	 */
	public void setGender(java.lang.String gender) {
		set("gender", gender);
	}
	
	/**
	 * 用户性别 注：0、男 1、女
	 */
	public java.lang.String getGender() {
		return getStr("gender");
	}
	
	/**
	 * 出生年月日
	 */
	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}
	
	/**
	 * 出生年月日
	 */
	public java.util.Date getBirthday() {
		return get("birthday");
	}
	
	/**
	 * 身份证号码
	 */
	public void setCardId(java.lang.String cardId) {
		set("card_id", cardId);
	}
	
	/**
	 * 身份证号码
	 */
	public java.lang.String getCardId() {
		return getStr("card_id");
	}
	
	/**
	 * 身份证正面照片
	 */
	public void setCardFront(java.lang.String cardFront) {
		set("card_front", cardFront);
	}
	
	/**
	 * 身份证正面照片
	 */
	public java.lang.String getCardFront() {
		return getStr("card_front");
	}
	
	/**
	 * 身份证背面照片
	 */
	public void setCardBack(java.lang.String cardBack) {
		set("card_back", cardBack);
	}
	
	/**
	 * 身份证背面照片
	 */
	public java.lang.String getCardBack() {
		return getStr("card_back");
	}
	
	/**
	 * 身份证有效期
	 */
	public void setCardValidity(java.util.Date cardValidity) {
		set("card_validity", cardValidity);
	}
	
	/**
	 * 身份证有效期
	 */
	public java.util.Date getCardValidity() {
		return get("card_validity");
	}
	
	/**
	 * 民族 注：平台字典
	 */
	public void setNation(java.lang.Integer nation) {
		set("nation", nation);
	}
	
	/**
	 * 民族 注：平台字典
	 */
	public java.lang.Integer getNation() {
		return getInt("nation");
	}
	
	/**
	 * 婚姻状况 注：0、已婚1、未婚
	 */
	public void setMaritalStatus(java.lang.Integer maritalStatus) {
		set("marital_status", maritalStatus);
	}
	
	/**
	 * 婚姻状况 注：0、已婚1、未婚
	 */
	public java.lang.Integer getMaritalStatus() {
		return getInt("marital_status");
	}
	
	/**
	 * 籍贯
	 */
	public void setNativePlace(java.lang.String nativePlace) {
		set("native_place", nativePlace);
	}
	
	/**
	 * 籍贯
	 */
	public java.lang.String getNativePlace() {
		return getStr("native_place");
	}
	
	/**
	 * 家庭住址
	 */
	public void setFamilyAddress(java.lang.String familyAddress) {
		set("family_address", familyAddress);
	}
	
	/**
	 * 家庭住址
	 */
	public java.lang.String getFamilyAddress() {
		return getStr("family_address");
	}
	
	/**
	 * 签发机关
	 */
	public void setIssuingAuthority(java.lang.String issuingAuthority) {
		set("issuing_authority", issuingAuthority);
	}
	
	/**
	 * 签发机关
	 */
	public java.lang.String getIssuingAuthority() {
		return getStr("issuing_authority");
	}
	
	/**
	 * 政治面貌
	 */
	public void setPoliticalStatus(java.lang.String politicalStatus) {
		set("political_status", politicalStatus);
	}
	
	/**
	 * 政治面貌
	 */
	public java.lang.String getPoliticalStatus() {
		return getStr("political_status");
	}
	
	/**
	 * 特长
	 */
	public void setSpeciality(java.lang.String speciality) {
		set("speciality", speciality);
	}
	
	/**
	 * 特长
	 */
	public java.lang.String getSpeciality() {
		return getStr("speciality");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	/**
	 * 个人中心头像路径 注：近照照片
	 */
	public void setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
	}
	
	/**
	 * 个人中心头像路径 注：近照照片
	 */
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}
	
	/**
	 * 头像原文件groupcode
	 */
	public void setSourceCode(java.lang.String sourceCode) {
		set("source_code", sourceCode);
	}
	
	/**
	 * 头像原文件groupcode
	 */
	public java.lang.String getSourceCode() {
		return getStr("source_code");
	}
	
	/**
	 * 头像原文件地址
	 */
	public void setSourceUrl(java.lang.String sourceUrl) {
		set("source_url", sourceUrl);
	}
	
	/**
	 * 头像原文件地址
	 */
	public java.lang.String getSourceUrl() {
		return getStr("source_url");
	}
	
	/**
	 * 二维码地址
	 */
	public void setQrCode(java.lang.String qrCode) {
		set("qr_code", qrCode);
	}
	
	/**
	 * 二维码地址
	 */
	public java.lang.String getQrCode() {
		return getStr("qr_code");
	}
	
	/**
	 * 开户行
	 */
	public void setBankName(java.lang.String bankName) {
		set("bank_name", bankName);
	}
	
	/**
	 * 开户行
	 */
	public java.lang.String getBankName() {
		return getStr("bank_name");
	}
	
	/**
	 * 银行卡号
	 */
	public void setBankCard(java.lang.String bankCard) {
		set("bank_card", bankCard);
	}
	
	/**
	 * 银行卡号
	 */
	public java.lang.String getBankCard() {
		return getStr("bank_card");
	}
	
	/**
	 * 紧急联系人
	 */
	public void setEmergencyContact(java.lang.String emergencyContact) {
		set("emergency_contact", emergencyContact);
	}
	
	/**
	 * 紧急联系人
	 */
	public java.lang.String getEmergencyContact() {
		return getStr("emergency_contact");
	}
	
	/**
	 * 紧急联系人电话
	 */
	public void setEmergencyContactPhone(java.lang.String emergencyContactPhone) {
		set("emergency_contact_phone", emergencyContactPhone);
	}
	
	/**
	 * 紧急联系人电话
	 */
	public java.lang.String getEmergencyContactPhone() {
		return getStr("emergency_contact_phone");
	}
	
}
