package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTmApprovalFlow<M extends BaseTmApprovalFlow<M>> extends Model<M> implements IBean {

	/**
	 * 审批流程ID
	 */
	public void setFlowId(java.lang.Long flowId) {
		set("flow_id", flowId);
	}
	
	/**
	 * 审批流程ID
	 */
	public java.lang.Long getFlowId() {
		return getLong("flow_id");
	}
	
	/**
	 * 流程名称
	 */
	public void setFlowName(java.lang.String flowName) {
		set("flow_name", flowName);
	}
	
	/**
	 * 流程名称
	 */
	public java.lang.String getFlowName() {
		return getStr("flow_name");
	}
	
	/**
	 * 是否删除 0、否 1、是
	 */
	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	/**
	 * 是否删除 0、否 1、是
	 */
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}
	
}
