package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEntCertificate<M extends BaseEntCertificate<M>> extends Model<M> implements IBean {

	/**
	 * 资质证书id
	 */
	public void setCertId(java.lang.Long certId) {
		set("cert_id", certId);
	}
	
	/**
	 * 资质证书id
	 */
	public java.lang.Long getCertId() {
		return getLong("cert_id");
	}
	
	/**
	 * 企业用户id
	 */
	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	/**
	 * 企业用户id
	 */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}
	
	/**
	 * 证书类型 注：平台字典索引
	 */
	public void setCertType(java.lang.String certType) {
		set("cert_type", certType);
	}
	
	/**
	 * 证书类型 注：平台字典索引
	 */
	public java.lang.String getCertType() {
		return getStr("cert_type");
	}
	
	/**
	 * 证书类型 注：平台字典，可自定义
	 */
	public void setCertTypeStr(java.lang.String certTypeStr) {
		set("cert_type_str", certTypeStr);
	}
	
	/**
	 * 证书类型 注：平台字典，可自定义
	 */
	public java.lang.String getCertTypeStr() {
		return getStr("cert_type_str");
	}
	
	/**
	 * 证书/荣誉名称
	 */
	public void setCertName(java.lang.String certName) {
		set("cert_name", certName);
	}
	
	/**
	 * 证书/荣誉名称
	 */
	public java.lang.String getCertName() {
		return getStr("cert_name");
	}
	
	/**
	 * 证书编号
	 */
	public void setCertNumber(java.lang.String certNumber) {
		set("cert_number", certNumber);
	}
	
	/**
	 * 证书编号
	 */
	public java.lang.String getCertNumber() {
		return getStr("cert_number");
	}
	
	/**
	 * 取得日期
	 */
	public void setIssueTime(java.util.Date issueTime) {
		set("issue_time", issueTime);
	}
	
	/**
	 * 取得日期
	 */
	public java.util.Date getIssueTime() {
		return get("issue_time");
	}
	
	/**
	 * 有限期至 注：具体时间或长期有效
	 */
	public void setLimitTime(java.util.Date limitTime) {
		set("limit_time", limitTime);
	}
	
	/**
	 * 有限期至 注：具体时间或长期有效
	 */
	public java.util.Date getLimitTime() {
		return get("limit_time");
	}
	
	/**
	 * 是否长期 注0、是 1、否 默认值1
	 */
	public void setIsLongTime(java.lang.Integer isLongTime) {
		set("is_long_time", isLongTime);
	}
	
	/**
	 * 是否长期 注0、是 1、否 默认值1
	 */
	public java.lang.Integer getIsLongTime() {
		return getInt("is_long_time");
	}
	
	/**
	 * 证书/荣誉说明
	 */
	public void setCertRemark(java.lang.String certRemark) {
		set("cert_remark", certRemark);
	}
	
	/**
	 * 证书/荣誉说明
	 */
	public java.lang.String getCertRemark() {
		return getStr("cert_remark");
	}
	
	/**
	 * 资质证书封面
	 */
	public void setCertCover(java.lang.String certCover) {
		set("cert_cover", certCover);
	}
	
	/**
	 * 资质证书封面
	 */
	public java.lang.String getCertCover() {
		return getStr("cert_cover");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}
	
}
