package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseConstructionUnit<M extends BaseConstructionUnit<M>> extends Model<M> implements IBean {

	/**
	 * 参建单位ID
	 */
	public void setUnitId(java.lang.Long unitId) {
		set("unit_id", unitId);
	}
	
	/**
	 * 参建单位ID
	 */
	public java.lang.Long getUnitId() {
		return getLong("unit_id");
	}
	
	/**
	 * xmgl平台组织ID
	 */
	public void setOrgId(java.lang.Long orgId) {
		set("org_id", orgId);
	}
	
	/**
	 * xmgl平台组织ID
	 */
	public java.lang.Long getOrgId() {
		return getLong("org_id");
	}
	
	/**
	 * 项目ID
	 */
	public void setProjId(java.lang.Long projId) {
		set("proj_id", projId);
	}
	
	/**
	 * 项目ID
	 */
	public java.lang.Long getProjId() {
		return getLong("proj_id");
	}
	
	/**
	 * 项目管理平台ID
	 */
	public void setProjOrgId(java.lang.Long projOrgId) {
		set("proj_org_id", projOrgId);
	}
	
	/**
	 * 项目管理平台ID
	 */
	public java.lang.Long getProjOrgId() {
		return getLong("proj_org_id");
	}
	
	/**
	 * 单位名称
	 */
	public void setUnitName(java.lang.String unitName) {
		set("unit_name", unitName);
	}
	
	/**
	 * 单位名称
	 */
	public java.lang.String getUnitName() {
		return getStr("unit_name");
	}
	
	/**
	 * 统一社会信用代码
	 */
	public void setCreditCode(java.lang.String creditCode) {
		set("credit_code", creditCode);
	}
	
	/**
	 * 统一社会信用代码
	 */
	public java.lang.String getCreditCode() {
		return getStr("credit_code");
	}
	
	/**
	 * 状态
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 类型
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 类型
	 */
	public java.lang.String getType() {
		return getStr("type");
	}
	
	/**
	 * 排序字段
	 */
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	/**
	 * 排序字段
	 */
	public java.lang.Integer getSort() {
		return getInt("sort");
	}
	
	/**
	 * 简称
	 */
	public void setShortName(java.lang.String shortName) {
		set("short_name", shortName);
	}
	
	/**
	 * 简称
	 */
	public java.lang.String getShortName() {
		return getStr("short_name");
	}
	
	/**
	 * 是否删除 0、是 1、否
	 */
	public void setIsDelete(java.lang.String isDelete) {
		set("is_delete", isDelete);
	}
	
	/**
	 * 是否删除 0、是 1、否
	 */
	public java.lang.String getIsDelete() {
		return getStr("is_delete");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}
	
}
