package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysDept<M extends BaseSysDept<M>> extends Model<M> implements IBean {

	/**
	 * 部门id
	 */
	public void setDeptId(java.lang.Long deptId) {
		set("dept_id", deptId);
	}
	
	/**
	 * 部门id
	 */
	public java.lang.Long getDeptId() {
		return getLong("dept_id");
	}
	
	/**
	 * 企业id
	 */
	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	/**
	 * 企业id
	 */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}
	
	/**
	 * 父部门id
	 */
	public void setParentId(java.lang.Long parentId) {
		set("parent_id", parentId);
	}
	
	/**
	 * 父部门id
	 */
	public java.lang.Long getParentId() {
		return getLong("parent_id");
	}
	
	/**
	 * 祖级列表
	 */
	public void setAncestors(java.lang.String ancestors) {
		set("ancestors", ancestors);
	}
	
	/**
	 * 祖级列表
	 */
	public java.lang.String getAncestors() {
		return getStr("ancestors");
	}
	
	/**
	 * 部门名称
	 */
	public void setDeptName(java.lang.String deptName) {
		set("dept_name", deptName);
	}
	
	/**
	 * 部门名称
	 */
	public java.lang.String getDeptName() {
		return getStr("dept_name");
	}
	
	/**
	 * 显示顺序
	 */
	public void setOrderNum(java.lang.Integer orderNum) {
		set("order_num", orderNum);
	}
	
	/**
	 * 显示顺序
	 */
	public java.lang.Integer getOrderNum() {
		return getInt("order_num");
	}
	
	/**
	 * 负责人
	 */
	public void setLeader(java.lang.String leader) {
		set("leader", leader);
	}
	
	/**
	 * 负责人
	 */
	public java.lang.String getLeader() {
		return getStr("leader");
	}
	
	/**
	 * 联系电话
	 */
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	/**
	 * 联系电话
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}
	
	/**
	 * 邮箱
	 */
	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	/**
	 * 邮箱
	 */
	public java.lang.String getEmail() {
		return getStr("email");
	}
	
	/**
	 * 部门状态（0正常 1停用）
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 部门状态（0正常 1停用）
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 部门级别
	 */
	public void setDeptLevel(java.lang.Integer deptLevel) {
		set("dept_level", deptLevel);
	}
	
	/**
	 * 部门级别
	 */
	public java.lang.Integer getDeptLevel() {
		return getInt("dept_level");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}
	
}
