package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOmRoleMenuDefault<M extends BaseOmRoleMenuDefault<M>> extends Model<M> implements IBean {

	/**
	 * 角色ID
	 */
	public void setRoleId(java.lang.Long roleId) {
		set("role_id", roleId);
	}
	
	/**
	 * 角色ID
	 */
	public java.lang.Long getRoleId() {
		return getLong("role_id");
	}
	
	/**
	 * 菜单ID
	 */
	public void setMenuId(java.lang.Long menuId) {
		set("menu_id", menuId);
	}
	
	/**
	 * 菜单ID
	 */
	public java.lang.Long getMenuId() {
		return getLong("menu_id");
	}
	
}
