package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTmApproval<M extends BaseTmApproval<M>> extends Model<M> implements IBean {

	/**
	 * 审批节点ID
	 */
	public void setApprId(java.lang.Long apprId) {
		set("appr_id", apprId);
	}
	
	/**
	 * 审批节点ID
	 */
	public java.lang.Long getApprId() {
		return getLong("appr_id");
	}
	
	/**
	 * 审批流程ID
	 */
	public void setFlowId(java.lang.Long flowId) {
		set("flow_id", flowId);
	}
	
	/**
	 * 审批流程ID
	 */
	public java.lang.Long getFlowId() {
		return getLong("flow_id");
	}
	
	/**
	 * 审批人员ID
	 */
	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	/**
	 * 审批人员ID
	 */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}
	
	/**
	 * 显示顺序
	 */
	public void setOrderNum(java.lang.Integer orderNum) {
		set("order_num", orderNum);
	}
	
	/**
	 * 显示顺序
	 */
	public java.lang.Integer getOrderNum() {
		return getInt("order_num");
	}
	
	/**
	 * 节点状态 1、正常 2、无权限 3、暂停
	 */
	public void setState(java.lang.String state) {
		set("state", state);
	}
	
	/**
	 * 节点状态 1、正常 2、无权限 3、暂停
	 */
	public java.lang.String getState() {
		return getStr("state");
	}
	
	/**
	 * 是否删除 0、否 1、是
	 */
	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	/**
	 * 是否删除 0、否 1、是
	 */
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}
	
}
