package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUserProject<M extends BaseSysUserProject<M>> extends Model<M> implements IBean {

	/**
	 * 用户ID
	 */
	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户ID
	 */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}
	
	/**
	 * 项目ID
	 */
	public void setProjId(java.lang.Long projId) {
		set("proj_id", projId);
	}
	
	/**
	 * 项目ID
	 */
	public java.lang.Long getProjId() {
		return getLong("proj_id");
	}
	
	/**
	 * 加入时间或参建时间
	 */
	public void setJoinTime(java.util.Date joinTime) {
		set("join_time", joinTime);
	}
	
	/**
	 * 加入时间或参建时间
	 */
	public java.util.Date getJoinTime() {
		return get("join_time");
	}
	
	/**
	 * 退出时间
	 */
	public void setQuitTime(java.util.Date quitTime) {
		set("quit_time", quitTime);
	}
	
	/**
	 * 退出时间
	 */
	public java.util.Date getQuitTime() {
		return get("quit_time");
	}
	
	/**
	 * 项目评价
	 */
	public void setProjAppraise(java.lang.String projAppraise) {
		set("proj_appraise", projAppraise);
	}
	
	/**
	 * 项目评价
	 */
	public java.lang.String getProjAppraise() {
		return getStr("proj_appraise");
	}
	
	/**
	 * 是否删除 0、是 1、否
	 */
	public void setIsDelete(java.lang.String isDelete) {
		set("is_delete", isDelete);
	}
	
	/**
	 * 是否删除 0、是 1、否
	 */
	public java.lang.String getIsDelete() {
		return getStr("is_delete");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}
	
}
