package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysOperLog<M extends BaseSysOperLog<M>> extends Model<M> implements IBean {

	/**
	 * 日志主键
	 */
	public void setOperId(java.lang.Long operId) {
		set("oper_id", operId);
	}
	
	/**
	 * 日志主键
	 */
	public java.lang.Long getOperId() {
		return getLong("oper_id");
	}
	
	/**
	 * 模块标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 模块标题
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}
	
	/**
	 * 业务类型（0其它 1新增 2修改 3删除）
	 */
	public void setBusinessType(java.lang.Integer businessType) {
		set("business_type", businessType);
	}
	
	/**
	 * 业务类型（0其它 1新增 2修改 3删除）
	 */
	public java.lang.Integer getBusinessType() {
		return getInt("business_type");
	}
	
	/**
	 * 方法名称
	 */
	public void setMethod(java.lang.String method) {
		set("method", method);
	}
	
	/**
	 * 方法名称
	 */
	public java.lang.String getMethod() {
		return getStr("method");
	}
	
	/**
	 * 请求方式
	 */
	public void setRequestMethod(java.lang.String requestMethod) {
		set("request_method", requestMethod);
	}
	
	/**
	 * 请求方式
	 */
	public java.lang.String getRequestMethod() {
		return getStr("request_method");
	}
	
	/**
	 * 操作类别（0其它 1后台用户 2手机端用户）
	 */
	public void setOperatorType(java.lang.Integer operatorType) {
		set("operator_type", operatorType);
	}
	
	/**
	 * 操作类别（0其它 1后台用户 2手机端用户）
	 */
	public java.lang.Integer getOperatorType() {
		return getInt("operator_type");
	}
	
	/**
	 * 操作人员
	 */
	public void setOperName(java.lang.String operName) {
		set("oper_name", operName);
	}
	
	/**
	 * 操作人员
	 */
	public java.lang.String getOperName() {
		return getStr("oper_name");
	}
	
	/**
	 * 部门名称
	 */
	public void setDeptName(java.lang.String deptName) {
		set("dept_name", deptName);
	}
	
	/**
	 * 部门名称
	 */
	public java.lang.String getDeptName() {
		return getStr("dept_name");
	}
	
	/**
	 * 请求URL
	 */
	public void setOperUrl(java.lang.String operUrl) {
		set("oper_url", operUrl);
	}
	
	/**
	 * 请求URL
	 */
	public java.lang.String getOperUrl() {
		return getStr("oper_url");
	}
	
	/**
	 * 主机地址
	 */
	public void setOperIp(java.lang.String operIp) {
		set("oper_ip", operIp);
	}
	
	/**
	 * 主机地址
	 */
	public java.lang.String getOperIp() {
		return getStr("oper_ip");
	}
	
	/**
	 * 操作地点
	 */
	public void setOperLocation(java.lang.String operLocation) {
		set("oper_location", operLocation);
	}
	
	/**
	 * 操作地点
	 */
	public java.lang.String getOperLocation() {
		return getStr("oper_location");
	}
	
	/**
	 * 请求参数
	 */
	public void setOperParam(java.lang.String operParam) {
		set("oper_param", operParam);
	}
	
	/**
	 * 请求参数
	 */
	public java.lang.String getOperParam() {
		return getStr("oper_param");
	}
	
	/**
	 * 返回参数
	 */
	public void setJsonResult(java.lang.String jsonResult) {
		set("json_result", jsonResult);
	}
	
	/**
	 * 返回参数
	 */
	public java.lang.String getJsonResult() {
		return getStr("json_result");
	}
	
	/**
	 * 操作状态（0正常 1异常）
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 操作状态（0正常 1异常）
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 错误消息
	 */
	public void setErrorMsg(java.lang.String errorMsg) {
		set("error_msg", errorMsg);
	}
	
	/**
	 * 错误消息
	 */
	public java.lang.String getErrorMsg() {
		return getStr("error_msg");
	}
	
	/**
	 * 操作时间
	 */
	public void setOperTime(java.util.Date operTime) {
		set("oper_time", operTime);
	}
	
	/**
	 * 操作时间
	 */
	public java.util.Date getOperTime() {
		return get("oper_time");
	}
	
}
