package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTmeProcess<M extends BaseTmeProcess<M>> extends Model<M> implements IBean {

	/**
	 * 工序ID
	 */
	public void setPrcId(java.lang.Long prcId) {
		set("prc_id", prcId);
	}
	
	/**
	 * 工序ID
	 */
	public java.lang.Long getPrcId() {
		return getLong("prc_id");
	}
	
	/**
	 * 企业ID
	 */
	public void setEntId(java.lang.Long entId) {
		set("ent_id", entId);
	}
	
	/**
	 * 企业ID
	 */
	public java.lang.Long getEntId() {
		return getLong("ent_id");
	}
	
	/**
	 * 工序编号
	 */
	public void setNumber(java.lang.String number) {
		set("number", number);
	}
	
	/**
	 * 工序编号
	 */
	public java.lang.String getNumber() {
		return getStr("number");
	}
	
	/**
	 * 工序名称
	 */
	public void setPrcName(java.lang.String prcName) {
		set("prc_name", prcName);
	}
	
	/**
	 * 工序名称
	 */
	public java.lang.String getPrcName() {
		return getStr("prc_name");
	}
	
	/**
	 * 前置任务类型
	 */
	public void setPreposeType(java.lang.String preposeType) {
		set("prepose_type", preposeType);
	}
	
	/**
	 * 前置任务类型
	 */
	public java.lang.String getPreposeType() {
		return getStr("prepose_type");
	}
	
	/**
	 * 延迟时间
	 */
	public void setDelayTime(java.util.Date delayTime) {
		set("delay_time", delayTime);
	}
	
	/**
	 * 延迟时间
	 */
	public java.util.Date getDelayTime() {
		return get("delay_time");
	}
	
	/**
	 * 是否删除 0、否 1、是
	 */
	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	/**
	 * 是否删除 0、否 1、是
	 */
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}
	
}
