package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTmApprovalLog<M extends BaseTmApprovalLog<M>> extends Model<M> implements IBean {

	/**
	 * 审批日志ID
	 */
	public void setLogId(java.lang.Long logId) {
		set("log_id", logId);
	}
	
	/**
	 * 审批日志ID
	 */
	public java.lang.Long getLogId() {
		return getLong("log_id");
	}
	
	/**
	 * 用户ID
	 */
	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户ID
	 */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}
	
	/**
	 * 审批流程ID
	 */
	public void setFlowId(java.lang.Long flowId) {
		set("flow_id", flowId);
	}
	
	/**
	 * 审批流程ID
	 */
	public java.lang.Long getFlowId() {
		return getLong("flow_id");
	}
	
	/**
	 * 审批节点ID
	 */
	public void setApprId(java.lang.Long apprId) {
		set("appr_id", apprId);
	}
	
	/**
	 * 审批节点ID
	 */
	public java.lang.Long getApprId() {
		return getLong("appr_id");
	}
	
	/**
	 * 任务标准名称
	 */
	public void setTaskName(java.lang.String taskName) {
		set("task_name", taskName);
	}
	
	/**
	 * 任务标准名称
	 */
	public java.lang.String getTaskName() {
		return getStr("task_name");
	}
	
	/**
	 * 审批结果类型 1、同意  2、驳回
	 */
	public void setResultType(java.lang.String resultType) {
		set("result_type", resultType);
	}
	
	/**
	 * 审批结果类型 1、同意  2、驳回
	 */
	public java.lang.String getResultType() {
		return getStr("result_type");
	}
	
	/**
	 * 审批状态 1、待审批  2、已完成
	 */
	public void setState(java.lang.String state) {
		set("state", state);
	}
	
	/**
	 * 审批状态 1、待审批  2、已完成
	 */
	public java.lang.String getState() {
		return getStr("state");
	}
	
	/**
	 * 审批意见
	 */
	public void setOpinion(java.lang.String opinion) {
		set("opinion", opinion);
	}
	
	/**
	 * 审批意见
	 */
	public java.lang.String getOpinion() {
		return getStr("opinion");
	}
	
	/**
	 * 提交审批时间
	 */
	public void setCommitTime(java.util.Date commitTime) {
		set("commit_time", commitTime);
	}
	
	/**
	 * 提交审批时间
	 */
	public java.util.Date getCommitTime() {
		return get("commit_time");
	}
	
	/**
	 * 完成审批时间
	 */
	public void setFinishTime(java.util.Date finishTime) {
		set("finish_time", finishTime);
	}
	
	/**
	 * 完成审批时间
	 */
	public java.util.Date getFinishTime() {
		return get("finish_time");
	}
	
	/**
	 * 是否删除 0、否 1、是
	 */
	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	/**
	 * 是否删除 0、否 1、是
	 */
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}
	
}
