package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBusinessDict<M extends BaseBusinessDict<M>> extends Model<M> implements IBean {

	/**
	 * 字典编码
	 */
	public void setDataId(java.lang.Long dataId) {
		set("data_id", dataId);
	}
	
	/**
	 * 字典编码
	 */
	public java.lang.Long getDataId() {
		return getLong("data_id");
	}
	
	/**
	 * 字典排序
	 */
	public void setDictSort(java.lang.Integer dictSort) {
		set("dict_sort", dictSort);
	}
	
	/**
	 * 字典排序
	 */
	public java.lang.Integer getDictSort() {
		return getInt("dict_sort");
	}
	
	/**
	 * 字典标签
	 */
	public void setDictLabel(java.lang.String dictLabel) {
		set("dict_label", dictLabel);
	}
	
	/**
	 * 字典标签
	 */
	public java.lang.String getDictLabel() {
		return getStr("dict_label");
	}
	
	/**
	 * 字典键值
	 */
	public void setDictValue(java.lang.String dictValue) {
		set("dict_value", dictValue);
	}
	
	/**
	 * 字典键值
	 */
	public java.lang.String getDictValue() {
		return getStr("dict_value");
	}
	
	/**
	 * 字典类型
	 */
	public void setDictType(java.lang.String dictType) {
		set("dict_type", dictType);
	}
	
	/**
	 * 字典类型
	 */
	public java.lang.String getDictType() {
		return getStr("dict_type");
	}
	
	/**
	 * 上一级数据ID
	 */
	public void setParentDataId(java.lang.Long parentDataId) {
		set("parent_data_id", parentDataId);
	}
	
	/**
	 * 上一级数据ID
	 */
	public java.lang.Long getParentDataId() {
		return getLong("parent_data_id");
	}
	
	/**
	 * 祖级列表
	 */
	public void setAncestors(java.lang.String ancestors) {
		set("ancestors", ancestors);
	}
	
	/**
	 * 祖级列表
	 */
	public java.lang.String getAncestors() {
		return getStr("ancestors");
	}
	
	/**
	 * 数据层级
	 */
	public void setDataLevel(java.lang.Integer dataLevel) {
		set("data_level", dataLevel);
	}
	
	/**
	 * 数据层级
	 */
	public java.lang.Integer getDataLevel() {
		return getInt("data_level");
	}
	
	/**
	 * 样式属性  注：其他样式扩展
	 */
	public void setCssClass(java.lang.String cssClass) {
		set("css_class", cssClass);
	}
	
	/**
	 * 样式属性  注：其他样式扩展
	 */
	public java.lang.String getCssClass() {
		return getStr("css_class");
	}
	
	/**
	 * 表格回显样式 注：自己制定几种样式所有统一样式
	 */
	public void setListClass(java.lang.String listClass) {
		set("list_class", listClass);
	}
	
	/**
	 * 表格回显样式 注：自己制定几种样式所有统一样式
	 */
	public java.lang.String getListClass() {
		return getStr("list_class");
	}
	
	/**
	 * 是否默认（Y是 N否）
	 */
	public void setIsDefault(java.lang.String isDefault) {
		set("is_default", isDefault);
	}
	
	/**
	 * 是否默认（Y是 N否）
	 */
	public java.lang.String getIsDefault() {
		return getStr("is_default");
	}
	
	/**
	 * 状态（0正常 1停用）
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态（0正常 1停用）
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}
	
}
