package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysLoginLog<M extends BaseSysLoginLog<M>> extends Model<M> implements IBean {

	/**
	 * 访问ID
	 */
	public void setLoginId(java.lang.Long loginId) {
		set("login_id", loginId);
	}
	
	/**
	 * 访问ID
	 */
	public java.lang.Long getLoginId() {
		return getLong("login_id");
	}
	
	/**
	 * 广联云用户ID
	 */
	public void setGlodonId(java.lang.Long glodonId) {
		set("glodon_id", glodonId);
	}
	
	/**
	 * 广联云用户ID
	 */
	public java.lang.Long getGlodonId() {
		return getLong("glodon_id");
	}
	
	/**
	 * 登录账号
	 */
	public void setLoginName(java.lang.String loginName) {
		set("login_name", loginName);
	}
	
	/**
	 * 登录账号
	 */
	public java.lang.String getLoginName() {
		return getStr("login_name");
	}
	
	/**
	 * 登录IP地址
	 */
	public void setIpaddr(java.lang.String ipaddr) {
		set("ipaddr", ipaddr);
	}
	
	/**
	 * 登录IP地址
	 */
	public java.lang.String getIpaddr() {
		return getStr("ipaddr");
	}
	
	/**
	 * 登录地点
	 */
	public void setLoginLocation(java.lang.String loginLocation) {
		set("login_location", loginLocation);
	}
	
	/**
	 * 登录地点
	 */
	public java.lang.String getLoginLocation() {
		return getStr("login_location");
	}
	
	/**
	 * 浏览器类型
	 */
	public void setBrowser(java.lang.String browser) {
		set("browser", browser);
	}
	
	/**
	 * 浏览器类型
	 */
	public java.lang.String getBrowser() {
		return getStr("browser");
	}
	
	/**
	 * 操作系统
	 */
	public void setOs(java.lang.String os) {
		set("os", os);
	}
	
	/**
	 * 操作系统
	 */
	public java.lang.String getOs() {
		return getStr("os");
	}
	
	/**
	 * 设备类型
	 */
	public void setDeviceType(java.lang.String deviceType) {
		set("device_type", deviceType);
	}
	
	/**
	 * 设备类型
	 */
	public java.lang.String getDeviceType() {
		return getStr("device_type");
	}
	
	/**
	 * 登录状态（0成功 1失败）
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 登录状态（0成功 1失败）
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 提示消息
	 */
	public void setMsg(java.lang.String msg) {
		set("msg", msg);
	}
	
	/**
	 * 提示消息
	 */
	public java.lang.String getMsg() {
		return getStr("msg");
	}
	
	/**
	 * 访问时间
	 */
	public void setLoginTime(java.util.Date loginTime) {
		set("login_time", loginTime);
	}
	
	/**
	 * 访问时间
	 */
	public java.util.Date getLoginTime() {
		return get("login_time");
	}
	
}
