package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEntQualification<M extends BaseEntQualification<M>> extends Model<M> implements IBean {

	/**
	 * 资质证书id
	 */
	public void setQualId(java.lang.Long qualId) {
		set("qual_id", qualId);
	}
	
	/**
	 * 资质证书id
	 */
	public java.lang.Long getQualId() {
		return getLong("qual_id");
	}
	
	/**
	 * 企业用户id
	 */
	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	/**
	 * 企业用户id
	 */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}
	
	/**
	 * 资质名称
	 */
	public void setQualName(java.lang.String qualName) {
		set("qual_name", qualName);
	}
	
	/**
	 * 资质名称
	 */
	public java.lang.String getQualName() {
		return getStr("qual_name");
	}
	
	/**
	 * 资质专业 注：平台字典索引
	 */
	public void setQualMajor(java.lang.String qualMajor) {
		set("qual_major", qualMajor);
	}
	
	/**
	 * 资质专业 注：平台字典索引
	 */
	public java.lang.String getQualMajor() {
		return getStr("qual_major");
	}
	
	/**
	 * 资质等级 注：平台字典索引
	 */
	public void setQualLevel(java.lang.String qualLevel) {
		set("qual_level", qualLevel);
	}
	
	/**
	 * 资质等级 注：平台字典索引
	 */
	public java.lang.String getQualLevel() {
		return getStr("qual_level");
	}
	
	/**
	 * 资质等级 注：平台字典，可自定义
	 */
	public void setQualLevelStr(java.lang.String qualLevelStr) {
		set("qual_level_str", qualLevelStr);
	}
	
	/**
	 * 资质等级 注：平台字典，可自定义
	 */
	public java.lang.String getQualLevelStr() {
		return getStr("qual_level_str");
	}
	
	/**
	 * 资质专业 注：平台字典，可自定义
	 */
	public void setQualMajorStr(java.lang.String qualMajorStr) {
		set("qual_major_str", qualMajorStr);
	}
	
	/**
	 * 资质专业 注：平台字典，可自定义
	 */
	public java.lang.String getQualMajorStr() {
		return getStr("qual_major_str");
	}
	
	/**
	 * 证书编号
	 */
	public void setQualNumber(java.lang.String qualNumber) {
		set("qual_number", qualNumber);
	}
	
	/**
	 * 证书编号
	 */
	public java.lang.String getQualNumber() {
		return getStr("qual_number");
	}
	
	/**
	 * 发证日期
	 */
	public void setIssueTime(java.util.Date issueTime) {
		set("issue_time", issueTime);
	}
	
	/**
	 * 发证日期
	 */
	public java.util.Date getIssueTime() {
		return get("issue_time");
	}
	
	/**
	 * 有限期至 注：具体时间或长期有效
	 */
	public void setLimitTime(java.util.Date limitTime) {
		set("limit_time", limitTime);
	}
	
	/**
	 * 有限期至 注：具体时间或长期有效
	 */
	public java.util.Date getLimitTime() {
		return get("limit_time");
	}
	
	/**
	 * 是否长期 注0、是 1、否 默认值1
	 */
	public void setIsLongTime(java.lang.Integer isLongTime) {
		set("is_long_time", isLongTime);
	}
	
	/**
	 * 是否长期 注0、是 1、否 默认值1
	 */
	public java.lang.Integer getIsLongTime() {
		return getInt("is_long_time");
	}
	
	/**
	 * 资质证书封面
	 */
	public void setQualCover(java.lang.String qualCover) {
		set("qual_cover", qualCover);
	}
	
	/**
	 * 资质证书封面
	 */
	public java.lang.String getQualCover() {
		return getStr("qual_cover");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}
	
}
