package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXmglUser<M extends BaseXmglUser<M>> extends Model<M> implements IBean {

	/**
	 * 自增ID
	 */
	public void setAutoId(java.lang.Long autoId) {
		set("auto_id", autoId);
	}
	
	/**
	 * 自增ID
	 */
	public java.lang.Long getAutoId() {
		return getLong("auto_id");
	}
	
	/**
	 * 用户ID
	 */
	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户ID
	 */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}
	
	/**
	 * 组织ID
	 */
	public void setOrgId(java.lang.Long orgId) {
		set("org_id", orgId);
	}
	
	/**
	 * 组织ID
	 */
	public java.lang.Long getOrgId() {
		return getLong("org_id");
	}
	
	/**
	 * 租户ID
	 */
	public void setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
	}
	
	/**
	 * 租户ID
	 */
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}
	
	/**
	 * 姓名
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 姓名
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 手机号
	 */
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	/**
	 * 手机号
	 */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}
	
	/**
	 * 邮箱
	 */
	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	/**
	 * 邮箱
	 */
	public java.lang.String getEmail() {
		return getStr("email");
	}
	
	/**
	 * 岗位
	 */
	public void setJobCodes(java.lang.String jobCodes) {
		set("jobCodes", jobCodes);
	}
	
	/**
	 * 岗位
	 */
	public java.lang.String getJobCodes() {
		return getStr("jobCodes");
	}
	
	/**
	 * 角色
	 */
	public void setRoles(java.lang.String roles) {
		set("roles", roles);
	}
	
	/**
	 * 角色
	 */
	public java.lang.String getRoles() {
		return getStr("roles");
	}
	
	/**
	 * 序号
	 */
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	/**
	 * 序号
	 */
	public java.lang.Integer getSort() {
		return getInt("sort");
	}
	
	/**
	 * 是否删除 0、否 1、是
	 */
	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}
	
	/**
	 * 是否删除 0、否 1、是
	 */
	public java.lang.Integer getIsDelete() {
		return getInt("is_delete");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}
	
}
