package com.demo.common.model.mysql.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOmOperUser<M extends BaseOmOperUser<M>> extends Model<M> implements IBean {

	/**
	 * 运营人员ID
	 */
	public void setOperId(java.lang.Long operId) {
		set("oper_id", operId);
	}
	
	/**
	 * 运营人员ID
	 */
	public java.lang.Long getOperId() {
		return getLong("oper_id");
	}
	
	/**
	 * 用户ID
	 */
	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户ID
	 */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}
	
	/**
	 * 加入时间
	 */
	public void setJoinTime(java.util.Date joinTime) {
		set("join_time", joinTime);
	}
	
	/**
	 * 加入时间
	 */
	public java.util.Date getJoinTime() {
		return get("join_time");
	}
	
}
