package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseBusinessDictBack;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusinessDictBack extends BaseBusinessDictBack<BusinessDictBack> {
	
}
