package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseBusinessDictTest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusinessDictTest extends BaseBusinessDictTest<BusinessDictTest> {
	
}
