package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseBusinessDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusinessDict extends BaseBusinessDict<BusinessDict> {
	
}
