package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseCertificate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Certificate extends BaseCertificate<Certificate> {
	
}
