package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseConstructionUnit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ConstructionUnit extends BaseConstructionUnit<ConstructionUnit> {
	
}
