package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseEntCertificate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EntCertificate extends BaseEntCertificate<EntCertificate> {
	
}
