package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseEntQualification;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EntQualification extends BaseEntQualification<EntQualification> {
	
}
