package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseJobLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JobLog extends BaseJobLog<JobLog> {
	
}
