package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseOmApp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OmApp extends BaseOmApp<OmApp> {
	
}
