package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseOmMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OmMenu extends BaseOmMenu<OmMenu> {
	
}
