package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseOmOperUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OmOperUser extends BaseOmOperUser<OmOperUser> {
	
}
