package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseOmOperLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OmOperLog extends BaseOmOperLog<OmOperLog> {
	
}
