package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseOmRoleMenuDefault;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OmRoleMenuDefault extends BaseOmRoleMenuDefault<OmRoleMenuDefault> {
	
}
