package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseOmRoleMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OmRoleMenu extends BaseOmRoleMenu<OmRoleMenu> {
	
}
