package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseOmRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OmRole extends BaseOmRole<OmRole> {
	
}
