package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseOmUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OmUserRole extends BaseOmUserRole<OmUserRole> {
	
}
