package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Project extends BaseProject<Project> {
	
}
