package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseProjectLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectLog extends BaseProjectLog<ProjectLog> {
	
}
