package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseSysApp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysApp extends BaseSysApp<SysApp> {
	
}
