package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseSysDictType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysDictType extends BaseSysDictType<SysDictType> {
	
}
