package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseSysDept;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysDept extends BaseSysDept<SysDept> {
	
}
