package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseSysDictData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysDictData extends BaseSysDictData<SysDictData> {
	
}
