package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseSysEntDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysEntDetail extends BaseSysEntDetail<SysEntDetail> {
	
}
