package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseSysEntProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysEntProject extends BaseSysEntProject<SysEntProject> {
	
}
