package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseSysLoginLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysLoginLog extends BaseSysLoginLog<SysLoginLog> {
	
}
