package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseSysMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysMenu extends BaseSysMenu<SysMenu> {
	
}
