package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseSysOperLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysOperLog extends BaseSysOperLog<SysOperLog> {
	
}
