package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseSysRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRole extends BaseSysRole<SysRole> {
	
}
