package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseSysRoleMenuDefault;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleMenuDefault extends BaseSysRoleMenuDefault<SysRoleMenuDefault> {
	
}
