package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseSysUserLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserLog extends BaseSysUserLog<SysUserLog> {
	
}
