package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseSysUserDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserDetail extends BaseSysUserDetail<SysUserDetail> {
	
}
