package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseSysUserDept;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserDept extends BaseSysUserDept<SysUserDept> {
	
}
