package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseSysUserWork;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserWork extends BaseSysUserWork<SysUserWork> {
	
}
