package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseSysUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUser extends BaseSysUser<SysUser> {
	
}
