package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseSysUserProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserProject extends BaseSysUserProject<SysUserProject> {
	
}
