package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseTmApproval;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TmApproval extends BaseTmApproval<TmApproval> {
	
}
