package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseTmApprovalFlow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TmApprovalFlow extends BaseTmApprovalFlow<TmApprovalFlow> {
	
}
