package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseTmApprovalLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TmApprovalLog extends BaseTmApprovalLog<TmApprovalLog> {
	
}
