package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseTmeAttachment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TmeAttachment extends BaseTmeAttachment<TmeAttachment> {
	
}
