package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseTmeProcessType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TmeProcessType extends BaseTmeProcessType<TmeProcessType> {
	
}
