package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseTmeProcessTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TmeProcessTask extends BaseTmeProcessTask<TmeProcessTask> {
	
}
