package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseTmeProcess;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TmeProcess extends BaseTmeProcess<TmeProcess> {
	
}
