package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseTmeRichText;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TmeRichText extends BaseTmeRichText<TmeRichText> {
	
}
