package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseTmeTaskStandard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TmeTaskStandard extends BaseTmeTaskStandard<TmeTaskStandard> {
	
}
