package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseTmeTaskStandardDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TmeTaskStandardDetail extends BaseTmeTaskStandardDetail<TmeTaskStandardDetail> {
	
}
