package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseTmeTaskStandardType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TmeTaskStandardType extends BaseTmeTaskStandardType<TmeTaskStandardType> {
	
}
