package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseTmpProcess;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TmpProcess extends BaseTmpProcess<TmpProcess> {
	
}
