package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseTmpProcessTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TmpProcessTask extends BaseTmpProcessTask<TmpProcessTask> {
	
}
