package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseTmpProcessType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TmpProcessType extends BaseTmpProcessType<TmpProcessType> {
	
}
