package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseTmpTaskStandardDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TmpTaskStandardDetail extends BaseTmpTaskStandardDetail<TmpTaskStandardDetail> {
	
}
