package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseTmpTaskStandardType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TmpTaskStandardType extends BaseTmpTaskStandardType<TmpTaskStandardType> {
	
}
