package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseTmpTaskStandard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TmpTaskStandard extends BaseTmpTaskStandard<TmpTaskStandard> {
	
}
