package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseUploadFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UploadFile extends BaseUploadFile<UploadFile> {
	
}
