package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseXmglOrgInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XmglOrgInfo extends BaseXmglOrgInfo<XmglOrgInfo> {
	
}
