package com.demo.common.model.mysql;

import com.demo.common.model.mysql.base.BaseXmglUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XmglUser extends BaseXmglUser<XmglUser> {
	
}
