package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWf2Notify<M extends BaseWf2Notify<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}
	
	public void setWfid(java.lang.String wfid) {
		set("wfid", wfid);
	}
	
	public java.lang.String getWfid() {
		return getStr("wfid");
	}
	
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public void setStartdate(java.util.Date startdate) {
		set("startdate", startdate);
	}
	
	public java.util.Date getStartdate() {
		return get("startdate");
	}
	
	public void setFinishdate(java.util.Date finishdate) {
		set("finishdate", finishdate);
	}
	
	public java.util.Date getFinishdate() {
		return get("finishdate");
	}
	
	public void setSenderid(java.lang.String senderid) {
		set("senderid", senderid);
	}
	
	public java.lang.String getSenderid() {
		return getStr("senderid");
	}
	
	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}
	
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setPositionname(java.lang.String positionname) {
		set("positionname", positionname);
	}
	
	public java.lang.String getPositionname() {
		return getStr("positionname");
	}
	
	public void setDeptid(java.lang.String deptid) {
		set("deptid", deptid);
	}
	
	public java.lang.String getDeptid() {
		return getStr("deptid");
	}
	
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}
	
	public void setSendername(java.lang.String sendername) {
		set("sendername", sendername);
	}
	
	public java.lang.String getSendername() {
		return getStr("sendername");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setX(java.lang.Integer x) {
		set("x", x);
	}
	
	public java.lang.Integer getX() {
		return getInt("x");
	}
	
}
