package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFax<M extends BaseFax<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setUpdatedate(java.util.Date updatedate) {
		set("updatedate", updatedate);
	}
	
	public java.util.Date getUpdatedate() {
		return get("updatedate");
	}
	
	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}
	
	public void setPrjid(java.lang.String prjid) {
		set("prjid", prjid);
	}
	
	public java.lang.String getPrjid() {
		return getStr("prjid");
	}
	
	public void setTjdate(java.util.Date tjdate) {
		set("tjdate", tjdate);
	}
	
	public java.util.Date getTjdate() {
		return get("tjdate");
	}
	
	public void setJsdate(java.util.Date jsdate) {
		set("jsdate", jsdate);
	}
	
	public java.util.Date getJsdate() {
		return get("jsdate");
	}
	
	public void setBhdate(java.util.Date bhdate) {
		set("bhdate", bhdate);
	}
	
	public java.util.Date getBhdate() {
		return get("bhdate");
	}
	
	public void setBackcontent(java.lang.String backcontent) {
		set("backcontent", backcontent);
	}
	
	public java.lang.String getBackcontent() {
		return getStr("backcontent");
	}
	
	public void setFwbh(java.lang.String fwbh) {
		set("fwbh", fwbh);
	}
	
	public java.lang.String getFwbh() {
		return getStr("fwbh");
	}
	
	public void setFwrq(java.util.Date fwrq) {
		set("fwrq", fwrq);
	}
	
	public java.util.Date getFwrq() {
		return get("fwrq");
	}
	
	public void setYs(java.lang.String ys) {
		set("ys", ys);
	}
	
	public java.lang.String getYs() {
		return getStr("ys");
	}
	
	public void setTm(java.lang.String tm) {
		set("tm", tm);
	}
	
	public java.lang.String getTm() {
		return getStr("tm");
	}
	
	public void setFz(java.lang.String fz) {
		set("fz", fz);
	}
	
	public java.lang.String getFz() {
		return getStr("fz");
	}
	
	public void setZs(java.lang.String zs) {
		set("zs", zs);
	}
	
	public java.lang.String getZs() {
		return getStr("zs");
	}
	
	public void setZw(java.lang.String zw) {
		set("zw", zw);
	}
	
	public java.lang.String getZw() {
		return getStr("zw");
	}
	
	public void setBb(java.lang.String bb) {
		set("bb", bb);
	}
	
	public java.lang.String getBb() {
		return getStr("bb");
	}
	
	public void setSfhw(java.lang.String sfhw) {
		set("sfhw", sfhw);
	}
	
	public java.lang.String getSfhw() {
		return getStr("sfhw");
	}
	
	public void setHwqx(java.util.Date hwqx) {
		set("hwqx", hwqx);
	}
	
	public java.util.Date getHwqx() {
		return get("hwqx");
	}
	
	public void setLwid(java.lang.String lwid) {
		set("lwid", lwid);
	}
	
	public java.lang.String getLwid() {
		return getStr("lwid");
	}
	
	public void setLwbh(java.lang.String lwbh) {
		set("lwbh", lwbh);
	}
	
	public java.lang.String getLwbh() {
		return getStr("lwbh");
	}
	
	public void setLwrq(java.util.Date lwrq) {
		set("lwrq", lwrq);
	}
	
	public java.util.Date getLwrq() {
		return get("lwrq");
	}
	
	public void setFwlx(java.lang.String fwlx) {
		set("fwlx", fwlx);
	}
	
	public java.lang.String getFwlx() {
		return getStr("fwlx");
	}
	
	public void setPspid(java.lang.String pspid) {
		set("pspid", pspid);
	}
	
	public java.lang.String getPspid() {
		return getStr("pspid");
	}
	
	public void setLotguid(java.lang.String lotguid) {
		set("lotguid", lotguid);
	}
	
	public java.lang.String getLotguid() {
		return getStr("lotguid");
	}
	
	public void setBzmc(java.lang.String bzmc) {
		set("bzmc", bzmc);
	}
	
	public java.lang.String getBzmc() {
		return getStr("bzmc");
	}
	
	public void setCid(java.lang.String cid) {
		set("cid", cid);
	}
	
	public java.lang.String getCid() {
		return getStr("cid");
	}
	
	public void setCname(java.lang.String cname) {
		set("cname", cname);
	}
	
	public java.lang.String getCname() {
		return getStr("cname");
	}
	
	public void setLotno(java.lang.String lotno) {
		set("lotno", lotno);
	}
	
	public java.lang.String getLotno() {
		return getStr("lotno");
	}
	
	public void setRid(java.lang.String rid) {
		set("rid", rid);
	}
	
	public java.lang.String getRid() {
		return getStr("rid");
	}
	
	public void setRname(java.lang.String rname) {
		set("rname", rname);
	}
	
	public java.lang.String getRname() {
		return getStr("rname");
	}
	
	public void setFldm(java.lang.String fldm) {
		set("fldm", fldm);
	}
	
	public java.lang.String getFldm() {
		return getStr("fldm");
	}
	
	public void setFlmc(java.lang.String flmc) {
		set("flmc", flmc);
	}
	
	public java.lang.String getFlmc() {
		return getStr("flmc");
	}
	
	public void setSpr1id(java.lang.String spr1id) {
		set("spr1id", spr1id);
	}
	
	public java.lang.String getSpr1id() {
		return getStr("spr1id");
	}
	
	public void setSpr1name(java.lang.String spr1name) {
		set("spr1name", spr1name);
	}
	
	public java.lang.String getSpr1name() {
		return getStr("spr1name");
	}
	
	public void setSpr2id(java.lang.String spr2id) {
		set("spr2id", spr2id);
	}
	
	public java.lang.String getSpr2id() {
		return getStr("spr2id");
	}
	
	public void setSpr2name(java.lang.String spr2name) {
		set("spr2name", spr2name);
	}
	
	public java.lang.String getSpr2name() {
		return getStr("spr2name");
	}
	
	public void setHydd(java.lang.String hydd) {
		set("hydd", hydd);
	}
	
	public java.lang.String getHydd() {
		return getStr("hydd");
	}
	
	public void setZydm(java.lang.String zydm) {
		set("zydm", zydm);
	}
	
	public java.lang.String getZydm() {
		return getStr("zydm");
	}
	
	public void setSpno(java.lang.String spno) {
		set("spno", spno);
	}
	
	public java.lang.String getSpno() {
		return getStr("spno");
	}
	
	public void setBh(java.lang.String bh) {
		set("bh", bh);
	}
	
	public java.lang.String getBh() {
		return getStr("bh");
	}
	
	public void setXh(java.lang.Integer xh) {
		set("xh", xh);
	}
	
	public java.lang.Integer getXh() {
		return getInt("xh");
	}
	
	public void setWftplid(java.lang.String wftplid) {
		set("wftplid", wftplid);
	}
	
	public java.lang.String getWftplid() {
		return getStr("wftplid");
	}
	
	public void setRefurl(java.lang.String refurl) {
		set("refurl", refurl);
	}
	
	public java.lang.String getRefurl() {
		return getStr("refurl");
	}
	
	public void setC1id(java.lang.String c1id) {
		set("c1id", c1id);
	}
	
	public java.lang.String getC1id() {
		return getStr("c1id");
	}
	
	public void setC1name(java.lang.String c1name) {
		set("c1name", c1name);
	}
	
	public java.lang.String getC1name() {
		return getStr("c1name");
	}
	
	public void setC2id(java.lang.String c2id) {
		set("c2id", c2id);
	}
	
	public java.lang.String getC2id() {
		return getStr("c2id");
	}
	
	public void setC2name(java.lang.String c2name) {
		set("c2name", c2name);
	}
	
	public java.lang.String getC2name() {
		return getStr("c2name");
	}
	
	public void setHtf(java.lang.String htf) {
		set("htf", htf);
	}
	
	public java.lang.String getHtf() {
		return getStr("htf");
	}
	
	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}
	
}
