package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBlog<M extends BaseBlog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("type", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("type");
	}

	public M setTitle(java.lang.String title) {
		set("mc", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("mc");
	}

	public M setContent(java.lang.String content) {
		set("userName", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("userName");
	}

}
