package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBx<M extends BaseBx<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setBh(java.lang.String bh) {
		set("bh", bh);
	}
	
	public java.lang.String getBh() {
		return getStr("bh");
	}
	
	public void setTm(java.lang.String tm) {
		set("tm", tm);
	}
	
	public java.lang.String getTm() {
		return getStr("tm");
	}
	
	public void setZw(java.lang.String zw) {
		set("zw", zw);
	}
	
	public java.lang.String getZw() {
		return getStr("zw");
	}
	
	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}
	
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}
	
	public void setPrjid(java.lang.String prjid) {
		set("prjid", prjid);
	}
	
	public java.lang.String getPrjid() {
		return getStr("prjid");
	}
	
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public void setXh(java.lang.Integer xh) {
		set("xh", xh);
	}
	
	public java.lang.Integer getXh() {
		return getInt("xh");
	}
	
	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}
	
	public void setUpdatedate(java.util.Date updatedate) {
		set("updatedate", updatedate);
	}
	
	public java.util.Date getUpdatedate() {
		return get("updatedate");
	}
	
	public void setYs(java.lang.Integer ys) {
		set("ys", ys);
	}
	
	public java.lang.Integer getYs() {
		return getInt("ys");
	}
	
	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}
	
	public java.math.BigDecimal getAmount() {
		return get("amount");
	}
	
	public void setHkdz(java.lang.String hkdz) {
		set("hkdz", hkdz);
	}
	
	public java.lang.String getHkdz() {
		return getStr("hkdz");
	}
	
	public void setJzdw(java.lang.String jzdw) {
		set("jzdw", jzdw);
	}
	
	public java.lang.String getJzdw() {
		return getStr("jzdw");
	}
	
	public void setSkdw(java.lang.String skdw) {
		set("skdw", skdw);
	}
	
	public java.lang.String getSkdw() {
		return getStr("skdw");
	}
	
	public void setBmmc(java.lang.String bmmc) {
		set("bmmc", bmmc);
	}
	
	public java.lang.String getBmmc() {
		return getStr("bmmc");
	}
	
	public void setYhmc(java.lang.String yhmc) {
		set("yhmc", yhmc);
	}
	
	public java.lang.String getYhmc() {
		return getStr("yhmc");
	}
	
	public void setYhzh(java.lang.String yhzh) {
		set("yhzh", yhzh);
	}
	
	public java.lang.String getYhzh() {
		return getStr("yhzh");
	}
	
	public void setJzrq(java.util.Date jzrq) {
		set("jzrq", jzrq);
	}
	
	public java.util.Date getJzrq() {
		return get("jzrq");
	}
	
	public void setBxrid(java.lang.String bxrid) {
		set("bxrid", bxrid);
	}
	
	public java.lang.String getBxrid() {
		return getStr("bxrid");
	}
	
	public void setBxrname(java.lang.String bxrname) {
		set("bxrname", bxrname);
	}
	
	public java.lang.String getBxrname() {
		return getStr("bxrname");
	}
	
	public void setBxrhrid(java.lang.String bxrhrid) {
		set("bxrhrid", bxrhrid);
	}
	
	public java.lang.String getBxrhrid() {
		return getStr("bxrhrid");
	}
	
	public void setSpr1id(java.lang.String spr1id) {
		set("spr1id", spr1id);
	}
	
	public java.lang.String getSpr1id() {
		return getStr("spr1id");
	}
	
	public void setSpr1name(java.lang.String spr1name) {
		set("spr1name", spr1name);
	}
	
	public java.lang.String getSpr1name() {
		return getStr("spr1name");
	}
	
	public void setSpr2id(java.lang.String spr2id) {
		set("spr2id", spr2id);
	}
	
	public java.lang.String getSpr2id() {
		return getStr("spr2id");
	}
	
	public void setSpr2name(java.lang.String spr2name) {
		set("spr2name", spr2name);
	}
	
	public java.lang.String getSpr2name() {
		return getStr("spr2name");
	}
	
	public void setSpr3id(java.lang.String spr3id) {
		set("spr3id", spr3id);
	}
	
	public java.lang.String getSpr3id() {
		return getStr("spr3id");
	}
	
	public void setSpr3name(java.lang.String spr3name) {
		set("spr3name", spr3name);
	}
	
	public java.lang.String getSpr3name() {
		return getStr("spr3name");
	}
	
	public void setWfid(java.lang.String wfid) {
		set("wfid", wfid);
	}
	
	public java.lang.String getWfid() {
		return getStr("wfid");
	}
	
	public void setTjrq(java.util.Date tjrq) {
		set("tjrq", tjrq);
	}
	
	public java.util.Date getTjrq() {
		return get("tjrq");
	}
	
	public void setBhrq(java.util.Date bhrq) {
		set("bhrq", bhrq);
	}
	
	public java.util.Date getBhrq() {
		return get("bhrq");
	}
	
	public void setBhyy(java.lang.String bhyy) {
		set("bhyy", bhyy);
	}
	
	public java.lang.String getBhyy() {
		return getStr("bhyy");
	}
	
}
