package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSupplierLot<M extends BaseSupplierLot<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setSupplierid(java.lang.String supplierid) {
		set("supplierid", supplierid);
	}
	
	public java.lang.String getSupplierid() {
		return getStr("supplierid");
	}
	
	public void setLotguid(java.lang.String lotguid) {
		set("lotguid", lotguid);
	}
	
	public java.lang.String getLotguid() {
		return getStr("lotguid");
	}
	
	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}
	
	public void setUpdatedate(java.util.Date updatedate) {
		set("updatedate", updatedate);
	}
	
	public java.util.Date getUpdatedate() {
		return get("updatedate");
	}
	
}
