package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLoginLog<M extends BaseLoginLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}
	
	public void setPrjid(java.lang.String prjid) {
		set("prjid", prjid);
	}
	
	public java.lang.String getPrjid() {
		return getStr("prjid");
	}
	
	public void setClientip(java.lang.String clientip) {
		set("clientip", clientip);
	}
	
	public java.lang.String getClientip() {
		return getStr("clientip");
	}
	
	public void setCountry(java.lang.String country) {
		set("country", country);
	}
	
	public java.lang.String getCountry() {
		return getStr("country");
	}
	
	public void setAdmcode(java.lang.Integer admcode) {
		set("admcode", admcode);
	}
	
	public java.lang.Integer getAdmcode() {
		return getInt("admcode");
	}
	
	public void setAdmcode1(java.lang.Integer admcode1) {
		set("admcode1", admcode1);
	}
	
	public java.lang.Integer getAdmcode1() {
		return getInt("admcode1");
	}
	
	public void setAdmcode2(java.lang.Integer admcode2) {
		set("admcode2", admcode2);
	}
	
	public java.lang.Integer getAdmcode2() {
		return getInt("admcode2");
	}
	
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setOs(java.lang.String os) {
		set("os", os);
	}
	
	public java.lang.String getOs() {
		return getStr("os");
	}
	
	public void setBrowser(java.lang.String browser) {
		set("browser", browser);
	}
	
	public java.lang.String getBrowser() {
		return getStr("browser");
	}
	
	public void setSessionid(java.lang.String sessionid) {
		set("sessionid", sessionid);
	}
	
	public java.lang.String getSessionid() {
		return getStr("sessionid");
	}
	
	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}
	
	public void setHost(java.lang.String host) {
		set("host", host);
	}
	
	public java.lang.String getHost() {
		return getStr("host");
	}
	
	public void setSysid(java.lang.String sysid) {
		set("sysid", sysid);
	}
	
	public java.lang.String getSysid() {
		return getStr("sysid");
	}
	
	public void setSystype(java.lang.String systype) {
		set("systype", systype);
	}
	
	public java.lang.String getSystype() {
		return getStr("systype");
	}
	
	public void setPrjtype(java.lang.String prjtype) {
		set("prjtype", prjtype);
	}
	
	public java.lang.String getPrjtype() {
		return getStr("prjtype");
	}
	
}
