package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePdAllow<M extends BasePdAllow<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setAllowid(java.lang.String allowid) {
		set("allowid", allowid);
	}
	
	public java.lang.String getAllowid() {
		return getStr("allowid");
	}
	
	public void setBelongid(java.lang.String belongid) {
		set("belongid", belongid);
	}
	
	public java.lang.String getBelongid() {
		return getStr("belongid");
	}
	
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}
	
}
