package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWfdata<M extends BaseWfdata<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}
	
	public void setPid(java.lang.String pid) {
		set("pid", pid);
	}
	
	public java.lang.String getPid() {
		return getStr("pid");
	}
	
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	public java.lang.Integer getSort() {
		return getInt("sort");
	}
	
	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}
	
	public void setUpdatedate(java.util.Date updatedate) {
		set("updatedate", updatedate);
	}
	
	public java.util.Date getUpdatedate() {
		return get("updatedate");
	}
	
	public void setEmployeeid(java.lang.String employeeid) {
		set("employeeid", employeeid);
	}
	
	public java.lang.String getEmployeeid() {
		return getStr("employeeid");
	}
	
	public void setEmployeename(java.lang.String employeename) {
		set("employeename", employeename);
	}
	
	public java.lang.String getEmployeename() {
		return getStr("employeename");
	}
	
	public void setOrgid(java.lang.String orgid) {
		set("orgid", orgid);
	}
	
	public java.lang.String getOrgid() {
		return getStr("orgid");
	}
	
	public void setOrgname(java.lang.String orgname) {
		set("orgname", orgname);
	}
	
	public java.lang.String getOrgname() {
		return getStr("orgname");
	}
	
	public void setPrjid(java.lang.String prjid) {
		set("prjid", prjid);
	}
	
	public java.lang.String getPrjid() {
		return getStr("prjid");
	}
	
	public void setPrjname(java.lang.String prjname) {
		set("prjname", prjname);
	}
	
	public java.lang.String getPrjname() {
		return getStr("prjname");
	}
	
	public void setPrjorgid(java.lang.String prjorgid) {
		set("prjorgid", prjorgid);
	}
	
	public java.lang.String getPrjorgid() {
		return getStr("prjorgid");
	}
	
	public void setPrjorgname(java.lang.String prjorgname) {
		set("prjorgname", prjorgname);
	}
	
	public java.lang.String getPrjorgname() {
		return getStr("prjorgname");
	}
	
	public void setJson(java.lang.String json) {
		set("json", json);
	}
	
	public java.lang.String getJson() {
		return getStr("json");
	}
	
	public void setReferenceurl(java.lang.String referenceurl) {
		set("referenceurl", referenceurl);
	}
	
	public java.lang.String getReferenceurl() {
		return getStr("referenceurl");
	}
	
	public void setBelongid(java.lang.String belongid) {
		set("belongid", belongid);
	}
	
	public java.lang.String getBelongid() {
		return getStr("belongid");
	}
	
	public void setRtype(java.lang.String rtype) {
		set("rtype", rtype);
	}
	
	public java.lang.String getRtype() {
		return getStr("rtype");
	}
	
}
