package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSupplierType<M extends BaseSupplierType<M>> extends Model<M> implements IBean {

	public void setDm(java.lang.String dm) {
		set("dm", dm);
	}
	
	public java.lang.String getDm() {
		return getStr("dm");
	}
	
	public void setMc(java.lang.String mc) {
		set("mc", mc);
	}
	
	public java.lang.String getMc() {
		return getStr("mc");
	}
	
}
