package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePdmType<M extends BasePdmType<M>> extends Model<M> implements IBean {

	public void setFldm(java.lang.String fldm) {
		set("fldm", fldm);
	}
	
	public java.lang.String getFldm() {
		return getStr("fldm");
	}
	
	public void setFlmc(java.lang.String flmc) {
		set("flmc", flmc);
	}
	
	public java.lang.String getFlmc() {
		return getStr("flmc");
	}
	
	public void setFlxh(java.lang.Integer flxh) {
		set("flxh", flxh);
	}
	
	public java.lang.Integer getFlxh() {
		return getInt("flxh");
	}
	
}
