package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFaxGf<M extends BaseFaxGf<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setBelongid(java.lang.String belongid) {
		set("belongid", belongid);
	}
	
	public java.lang.String getBelongid() {
		return getStr("belongid");
	}
	
	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}
	
	public void setUpdatedate(java.util.Date updatedate) {
		set("updatedate", updatedate);
	}
	
	public java.util.Date getUpdatedate() {
		return get("updatedate");
	}
	
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setTypename(java.lang.String typename) {
		set("typename", typename);
	}
	
	public java.lang.String getTypename() {
		return getStr("typename");
	}
	
	public void setRtype(java.lang.Integer rtype) {
		set("rtype", rtype);
	}
	
	public java.lang.Integer getRtype() {
		return getInt("rtype");
	}
	
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	public java.lang.Integer getSort() {
		return getInt("sort");
	}
	
	public void setText(java.lang.String text) {
		set("text", text);
	}
	
	public java.lang.String getText() {
		return getStr("text");
	}
	
	public void setC01bzmc(java.lang.String c01bzmc) {
		set("c01bzmc", c01bzmc);
	}
	
	public java.lang.String getC01bzmc() {
		return getStr("c01bzmc");
	}
	
	public void setC01gz(java.lang.String c01gz) {
		set("c01gz", c01gz);
	}
	
	public java.lang.String getC01gz() {
		return getStr("c01gz");
	}
	
	public void setC01rybl(java.lang.String c01rybl) {
		set("c01rybl", c01rybl);
	}
	
	public java.lang.String getC01rybl() {
		return getStr("c01rybl");
	}
	
	public void setC03xm(java.lang.String c03xm) {
		set("c03xm", c03xm);
	}
	
	public java.lang.String getC03xm() {
		return getStr("c03xm");
	}
	
	public void setC03gcl(java.lang.String c03gcl) {
		set("c03gcl", c03gcl);
	}
	
	public java.lang.String getC03gcl() {
		return getStr("c03gcl");
	}
	
	public void setC03jldw(java.lang.String c03jldw) {
		set("c03jldw", c03jldw);
	}
	
	public java.lang.String getC03jldw() {
		return getStr("c03jldw");
	}
	
	public void setC03gz(java.lang.String c03gz) {
		set("c03gz", c03gz);
	}
	
	public java.lang.String getC03gz() {
		return getStr("c03gz");
	}
	
	public void setC03rysl(java.lang.String c03rysl) {
		set("c03rysl", c03rysl);
	}
	
	public java.lang.String getC03rysl() {
		return getStr("c03rysl");
	}
	
	public void setC03gzsj(java.lang.String c03gzsj) {
		set("c03gzsj", c03gzsj);
	}
	
	public java.lang.String getC03gzsj() {
		return getStr("c03gzsj");
	}
	
	public void setC03bz(java.lang.String c03bz) {
		set("c03bz", c03bz);
	}
	
	public java.lang.String getC03bz() {
		return getStr("c03bz");
	}
	
	public void setC10dcgw(java.lang.String c10dcgw) {
		set("c10dcgw", c10dcgw);
	}
	
	public java.lang.String getC10dcgw() {
		return getStr("c10dcgw");
	}
	
	public void setC10phgw(java.lang.String c10phgw) {
		set("c10phgw", c10phgw);
	}
	
	public java.lang.String getC10phgw() {
		return getStr("c10phgw");
	}
	
	public void setC10gznr(java.lang.String c10gznr) {
		set("c10gznr", c10gznr);
	}
	
	public java.lang.String getC10gznr() {
		return getStr("c10gznr");
	}
	
	public void setC12jcr(java.lang.String c12jcr) {
		set("c12jcr", c12jcr);
	}
	
	public java.lang.String getC12jcr() {
		return getStr("c12jcr");
	}
	
	public void setC12jcnr(java.lang.String c12jcnr) {
		set("c12jcnr", c12jcnr);
	}
	
	public java.lang.String getC12jcnr() {
		return getStr("c12jcnr");
	}
	
	public void setC12jcpl(java.lang.String c12jcpl) {
		set("c12jcpl", c12jcpl);
	}
	
	public java.lang.String getC12jcpl() {
		return getStr("c12jcpl");
	}
	
	public void setC12xjzp(java.lang.String c12xjzp) {
		set("c12xjzp", c12xjzp);
	}
	
	public java.lang.String getC12xjzp() {
		return getStr("c12xjzp");
	}
	
}
