package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIdcard<M extends BaseIdcard<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setXm(java.lang.String xm) {
		set("xm", xm);
	}
	
	public java.lang.String getXm() {
		return getStr("xm");
	}
	
	public void setXb(java.lang.String xb) {
		set("xb", xb);
	}
	
	public java.lang.String getXb() {
		return getStr("xb");
	}
	
	public void setMz(java.lang.String mz) {
		set("mz", mz);
	}
	
	public java.lang.String getMz() {
		return getStr("mz");
	}
	
	public void setCsrq(java.util.Date csrq) {
		set("csrq", csrq);
	}
	
	public java.util.Date getCsrq() {
		return get("csrq");
	}
	
	public void setZz(java.lang.String zz) {
		set("zz", zz);
	}
	
	public java.lang.String getZz() {
		return getStr("zz");
	}
	
	public void setFzjg(java.lang.String fzjg) {
		set("fzjg", fzjg);
	}
	
	public java.lang.String getFzjg() {
		return getStr("fzjg");
	}
	
	public void setYxq(java.lang.String yxq) {
		set("yxq", yxq);
	}
	
	public java.lang.String getYxq() {
		return getStr("yxq");
	}
	
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}
	
	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}
	
	public void setUpdatedate(java.util.Date updatedate) {
		set("updatedate", updatedate);
	}
	
	public java.util.Date getUpdatedate() {
		return get("updatedate");
	}
	
}
