package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWfUrge<M extends BaseWfUrge<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setWfid(java.lang.String wfid) {
		set("wfid", wfid);
	}
	
	public java.lang.String getWfid() {
		return getStr("wfid");
	}
	
	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}
	
	public void setHrid(java.lang.Integer hrid) {
		set("hrid", hrid);
	}
	
	public java.lang.Integer getHrid() {
		return getInt("hrid");
	}
	
	public void setVerifykey(java.lang.String verifykey) {
		set("verifykey", verifykey);
	}
	
	public java.lang.String getVerifykey() {
		return getStr("verifykey");
	}
	
	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}
	
}
