package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSupplierLinkman<M extends BaseSupplierLinkman<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setSupplierid(java.lang.String supplierid) {
		set("supplierid", supplierid);
	}
	
	public java.lang.String getSupplierid() {
		return getStr("supplierid");
	}
	
	public void setSuppliercode(java.lang.String suppliercode) {
		set("suppliercode", suppliercode);
	}
	
	public java.lang.String getSuppliercode() {
		return getStr("suppliercode");
	}
	
	public void setSuppliername(java.lang.String suppliername) {
		set("suppliername", suppliername);
	}
	
	public java.lang.String getSuppliername() {
		return getStr("suppliername");
	}
	
	public void setHrid(java.lang.String hrid) {
		set("hrid", hrid);
	}
	
	public java.lang.String getHrid() {
		return getStr("hrid");
	}
	
	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}
	
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}
	
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}
	
	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}
	
	public void setTenderid(java.lang.String tenderid) {
		set("tenderid", tenderid);
	}
	
	public java.lang.String getTenderid() {
		return getStr("tenderid");
	}
	
	public void setPrjid(java.lang.String prjid) {
		set("prjid", prjid);
	}
	
	public java.lang.String getPrjid() {
		return getStr("prjid");
	}
	
	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
}
