package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWf2<M extends BaseWf2<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}
	
	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}
	
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setTypename(java.lang.String typename) {
		set("typename", typename);
	}
	
	public java.lang.String getTypename() {
		return getStr("typename");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setBelongid(java.lang.String belongid) {
		set("belongid", belongid);
	}
	
	public java.lang.String getBelongid() {
		return getStr("belongid");
	}
	
	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}
	
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}
	
	public void setPrjid(java.lang.String prjid) {
		set("prjid", prjid);
	}
	
	public java.lang.String getPrjid() {
		return getStr("prjid");
	}
	
	public void setXcount(java.lang.Integer xcount) {
		set("xcount", xcount);
	}
	
	public java.lang.Integer getXcount() {
		return getInt("xcount");
	}
	
	public void setStartdate(java.util.Date startdate) {
		set("startdate", startdate);
	}
	
	public java.util.Date getStartdate() {
		return get("startdate");
	}
	
	public void setFinishdate(java.util.Date finishdate) {
		set("finishdate", finishdate);
	}
	
	public java.util.Date getFinishdate() {
		return get("finishdate");
	}
	
	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}
	
	public void setPspid(java.lang.String pspid) {
		set("pspid", pspid);
	}
	
	public java.lang.String getPspid() {
		return getStr("pspid");
	}
	
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	public java.lang.Integer getSort() {
		return getInt("sort");
	}
	
	public void setSpNo(java.lang.String spNo) {
		set("sp_no", spNo);
	}
	
	public java.lang.String getSpNo() {
		return getStr("sp_no");
	}
	
	public void setUpdatedate(java.util.Date updatedate) {
		set("updatedate", updatedate);
	}
	
	public java.util.Date getUpdatedate() {
		return get("updatedate");
	}
	
	public void setTplid(java.lang.String tplid) {
		set("tplid", tplid);
	}
	
	public java.lang.String getTplid() {
		return getStr("tplid");
	}
	
	public void setTpltype(java.lang.Integer tpltype) {
		set("tpltype", tpltype);
	}
	
	public java.lang.Integer getTpltype() {
		return getInt("tpltype");
	}
	
	public void setBh(java.lang.String bh) {
		set("bh", bh);
	}
	
	public java.lang.String getBh() {
		return getStr("bh");
	}
	
	public void setCallback(java.lang.String callback) {
		set("callback", callback);
	}
	
	public java.lang.String getCallback() {
		return getStr("callback");
	}
	
	public void setCallbackTime(java.util.Date callbackTime) {
		set("callback_time", callbackTime);
	}
	
	public java.util.Date getCallbackTime() {
		return get("callback_time");
	}
	
}
