package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWf<M extends BaseWf<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setBelongid(java.lang.String belongid) {
		set("belongid", belongid);
	}
	
	public java.lang.String getBelongid() {
		return getStr("belongid");
	}
	
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}
	
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	public java.lang.Integer getSort() {
		return getInt("sort");
	}
	
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}
	
	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}
	
	public void setUpdatedate(java.util.Date updatedate) {
		set("updatedate", updatedate);
	}
	
	public java.util.Date getUpdatedate() {
		return get("updatedate");
	}
	
	public void setFinishdate(java.util.Date finishdate) {
		set("finishdate", finishdate);
	}
	
	public java.util.Date getFinishdate() {
		return get("finishdate");
	}
	
	public void setSummary(java.lang.String summary) {
		set("summary", summary);
	}
	
	public java.lang.String getSummary() {
		return getStr("summary");
	}
	
	public void setProgress(java.lang.Integer progress) {
		set("progress", progress);
	}
	
	public java.lang.Integer getProgress() {
		return getInt("progress");
	}
	
	public void setJson(java.lang.String json) {
		set("json", json);
	}
	
	public java.lang.String getJson() {
		return getStr("json");
	}
	
	public void setEmployeeid(java.lang.String employeeid) {
		set("employeeid", employeeid);
	}
	
	public java.lang.String getEmployeeid() {
		return getStr("employeeid");
	}
	
	public void setEmployeename(java.lang.String employeename) {
		set("employeename", employeename);
	}
	
	public java.lang.String getEmployeename() {
		return getStr("employeename");
	}
	
	public void setPrjid(java.lang.String prjid) {
		set("prjid", prjid);
	}
	
	public java.lang.String getPrjid() {
		return getStr("prjid");
	}
	
	public void setPrjname(java.lang.String prjname) {
		set("prjname", prjname);
	}
	
	public java.lang.String getPrjname() {
		return getStr("prjname");
	}
	
	public void setPrevwfid(java.lang.String prevwfid) {
		set("prevwfid", prevwfid);
	}
	
	public java.lang.String getPrevwfid() {
		return getStr("prevwfid");
	}
	
	public void setTypename(java.lang.String typename) {
		set("typename", typename);
	}
	
	public java.lang.String getTypename() {
		return getStr("typename");
	}
	
	public void setSpNo(java.lang.String spNo) {
		set("sp_no", spNo);
	}
	
	public java.lang.String getSpNo() {
		return getStr("sp_no");
	}
	
}
