package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMrpJhDetail<M extends BaseMrpJhDetail<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setBelongid(java.lang.String belongid) {
		set("belongid", belongid);
	}
	
	public java.lang.String getBelongid() {
		return getStr("belongid");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}
	
	public void setUpdatedate(java.util.Date updatedate) {
		set("updatedate", updatedate);
	}
	
	public java.util.Date getUpdatedate() {
		return get("updatedate");
	}
	
	public void setWlmc(java.lang.String wlmc) {
		set("wlmc", wlmc);
	}
	
	public java.lang.String getWlmc() {
		return getStr("wlmc");
	}
	
	public void setWlbh(java.lang.String wlbh) {
		set("wlbh", wlbh);
	}
	
	public java.lang.String getWlbh() {
		return getStr("wlbh");
	}
	
	public void setWlxh(java.lang.String wlxh) {
		set("wlxh", wlxh);
	}
	
	public java.lang.String getWlxh() {
		return getStr("wlxh");
	}
	
	public void setWllx(java.lang.String wllx) {
		set("wllx", wllx);
	}
	
	public java.lang.String getWllx() {
		return getStr("wllx");
	}
	
	public void setSylx(java.lang.String sylx) {
		set("sylx", sylx);
	}
	
	public java.lang.String getSylx() {
		return getStr("sylx");
	}
	
	public void setWlgg(java.lang.String wlgg) {
		set("wlgg", wlgg);
	}
	
	public java.lang.String getWlgg() {
		return getStr("wlgg");
	}
	
	public void setJhsl(java.math.BigDecimal jhsl) {
		set("jhsl", jhsl);
	}
	
	public java.math.BigDecimal getJhsl() {
		return get("jhsl");
	}
	
	public void setJldw(java.lang.String jldw) {
		set("jldw", jldw);
	}
	
	public java.lang.String getJldw() {
		return getStr("jldw");
	}
	
}
