package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFile<M extends BaseFile<M>> extends Model<M> implements IBean {

	public void setFileid(java.lang.String fileid) {
		set("fileid", fileid);
	}
	
	public java.lang.String getFileid() {
		return getStr("fileid");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setSize(java.lang.Integer size) {
		set("size", size);
	}
	
	public java.lang.Integer getSize() {
		return getInt("size");
	}
	
	public void setMime(java.lang.String mime) {
		set("mime", mime);
	}
	
	public java.lang.String getMime() {
		return getStr("mime");
	}
	
	public void setClientip(java.lang.String clientip) {
		set("clientip", clientip);
	}
	
	public java.lang.String getClientip() {
		return getStr("clientip");
	}
	
	public void setHost(java.lang.String host) {
		set("host", host);
	}
	
	public java.lang.String getHost() {
		return getStr("host");
	}
	
	public void setMd5(java.lang.String md5) {
		set("md5", md5);
	}
	
	public java.lang.String getMd5() {
		return getStr("md5");
	}
	
	public void setSha1(java.lang.String sha1) {
		set("sha1", sha1);
	}
	
	public java.lang.String getSha1() {
		return getStr("sha1");
	}
	
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}
	
	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}
	
	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}
	
	public void setBelongid(java.lang.String belongid) {
		set("belongid", belongid);
	}
	
	public java.lang.String getBelongid() {
		return getStr("belongid");
	}
	
	public void setPrjid(java.lang.String prjid) {
		set("prjid", prjid);
	}
	
	public java.lang.String getPrjid() {
		return getStr("prjid");
	}
	
}
