package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDoc<M extends BaseDoc<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setMd5(java.lang.String md5) {
		set("md5", md5);
	}
	
	public java.lang.String getMd5() {
		return getStr("md5");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setFiletype(java.lang.String filetype) {
		set("filetype", filetype);
	}
	
	public java.lang.String getFiletype() {
		return getStr("filetype");
	}
	
	public void setPid(java.lang.String pid) {
		set("pid", pid);
	}
	
	public java.lang.String getPid() {
		return getStr("pid");
	}
	
	public void setSize(java.lang.Long size) {
		set("size", size);
	}
	
	public java.lang.Long getSize() {
		return getLong("size");
	}
	
	public void setPrjid(java.lang.String prjid) {
		set("prjid", prjid);
	}
	
	public java.lang.String getPrjid() {
		return getStr("prjid");
	}
	
	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}
	
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setClientip(java.lang.String clientip) {
		set("clientip", clientip);
	}
	
	public java.lang.String getClientip() {
		return getStr("clientip");
	}
	
	public void setJson(java.lang.String json) {
		set("json", json);
	}
	
	public java.lang.String getJson() {
		return getStr("json");
	}
	
	public void setDowncount(java.lang.Integer downcount) {
		set("downcount", downcount);
	}
	
	public java.lang.Integer getDowncount() {
		return getInt("downcount");
	}
	
	public void setShareprj(java.lang.Integer shareprj) {
		set("shareprj", shareprj);
	}
	
	public java.lang.Integer getShareprj() {
		return getInt("shareprj");
	}
	
	public void setShareorg(java.lang.Integer shareorg) {
		set("shareorg", shareorg);
	}
	
	public java.lang.Integer getShareorg() {
		return getInt("shareorg");
	}
	
	public void setShareother(java.lang.Integer shareother) {
		set("shareother", shareother);
	}
	
	public java.lang.Integer getShareother() {
		return getInt("shareother");
	}
	
	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}
	
	public void setCid(java.lang.String cid) {
		set("cid", cid);
	}
	
	public java.lang.String getCid() {
		return getStr("cid");
	}
	
}
