package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysPage<M extends BaseSysPage<M>> extends Model<M> implements IBean {

	public void setPageid(java.lang.String pageid) {
		set("pageid", pageid);
	}
	
	public java.lang.String getPageid() {
		return getStr("pageid");
	}
	
	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}
	
	public void setData(java.lang.String data) {
		set("data", data);
	}
	
	public java.lang.String getData() {
		return getStr("data");
	}
	
	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}
	
	public void setVer(java.lang.Integer ver) {
		set("ver", ver);
	}
	
	public java.lang.Integer getVer() {
		return getInt("ver");
	}
	
	public void setAuthor(java.lang.String author) {
		set("author", author);
	}
	
	public java.lang.String getAuthor() {
		return getStr("author");
	}
	
	public void setEnabled(java.lang.String enabled) {
		set("enabled", enabled);
	}
	
	public java.lang.String getEnabled() {
		return getStr("enabled");
	}
	
}
