package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePrj<M extends BasePrj<M>> extends Model<M> implements IBean {

	public void setPrjid(java.lang.String prjid) {
		set("prjid", prjid);
	}
	
	public java.lang.String getPrjid() {
		return getStr("prjid");
	}
	
	public void setPrefixcode(java.lang.String prefixcode) {
		set("prefixcode", prefixcode);
	}
	
	public java.lang.String getPrefixcode() {
		return getStr("prefixcode");
	}
	
	public void setPrjname(java.lang.String prjname) {
		set("prjname", prjname);
	}
	
	public java.lang.String getPrjname() {
		return getStr("prjname");
	}
	
	public void setPrjorgcode(java.lang.String prjorgcode) {
		set("prjorgcode", prjorgcode);
	}
	
	public java.lang.String getPrjorgcode() {
		return getStr("prjorgcode");
	}
	
	public void setPrjorgname(java.lang.String prjorgname) {
		set("prjorgname", prjorgname);
	}
	
	public java.lang.String getPrjorgname() {
		return getStr("prjorgname");
	}
	
	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}
	
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}
	
	public void setOrgname(java.lang.String orgname) {
		set("orgname", orgname);
	}
	
	public java.lang.String getOrgname() {
		return getStr("orgname");
	}
	
	public void setOrgcode(java.lang.String orgcode) {
		set("orgcode", orgcode);
	}
	
	public java.lang.String getOrgcode() {
		return getStr("orgcode");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}
	
	public void setUpdatedate(java.util.Date updatedate) {
		set("updatedate", updatedate);
	}
	
	public java.util.Date getUpdatedate() {
		return get("updatedate");
	}
	
	public void setEngineeringid(java.lang.String engineeringid) {
		set("engineeringid", engineeringid);
	}
	
	public java.lang.String getEngineeringid() {
		return getStr("engineeringid");
	}
	
	public void setEngineeringname(java.lang.String engineeringname) {
		set("engineeringname", engineeringname);
	}
	
	public java.lang.String getEngineeringname() {
		return getStr("engineeringname");
	}
	
	public void setAdmcode2(java.lang.Integer admcode2) {
		set("admcode2", admcode2);
	}
	
	public java.lang.Integer getAdmcode2() {
		return getInt("admcode2");
	}
	
	public void setPrjcode(java.lang.String prjcode) {
		set("prjcode", prjcode);
	}
	
	public java.lang.String getPrjcode() {
		return getStr("prjcode");
	}
	
	public void setAdmname2(java.lang.String admname2) {
		set("admname2", admname2);
	}
	
	public java.lang.String getAdmname2() {
		return getStr("admname2");
	}
	
	public void setAdmcode1(java.lang.Integer admcode1) {
		set("admcode1", admcode1);
	}
	
	public java.lang.Integer getAdmcode1() {
		return getInt("admcode1");
	}
	
	public void setAdmname1(java.lang.String admname1) {
		set("admname1", admname1);
	}
	
	public java.lang.String getAdmname1() {
		return getStr("admname1");
	}
	
}
