package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}
	
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}
	
	public void setLoginname(java.lang.String loginname) {
		set("loginname", loginname);
	}
	
	public java.lang.String getLoginname() {
		return getStr("loginname");
	}
	
	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}
	
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}
	
	public void setIssms(java.lang.String issms) {
		set("issms", issms);
	}
	
	public java.lang.String getIssms() {
		return getStr("issms");
	}
	
	public void setHrid(java.lang.String hrid) {
		set("hrid", hrid);
	}
	
	public java.lang.String getHrid() {
		return getStr("hrid");
	}
	
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	public void setSupplierid(java.lang.String supplierid) {
		set("supplierid", supplierid);
	}
	
	public java.lang.String getSupplierid() {
		return getStr("supplierid");
	}
	
	public void setDeptid(java.lang.String deptid) {
		set("deptid", deptid);
	}
	
	public java.lang.String getDeptid() {
		return getStr("deptid");
	}
	
	public void setDeptname(java.lang.String deptname) {
		set("deptname", deptname);
	}
	
	public java.lang.String getDeptname() {
		return getStr("deptname");
	}
	
	public void setRoleids(java.lang.String roleids) {
		set("roleids", roleids);
	}
	
	public java.lang.String getRoleids() {
		return getStr("roleids");
	}
	
	public void setSignimgurl(java.lang.String signimgurl) {
		set("signimgurl", signimgurl);
	}
	
	public java.lang.String getSignimgurl() {
		return getStr("signimgurl");
	}
	
	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}
	
	public void setUpdatedate(java.util.Date updatedate) {
		set("updatedate", updatedate);
	}
	
	public java.util.Date getUpdatedate() {
		return get("updatedate");
	}
	
	public void setRolenames(java.lang.String rolenames) {
		set("rolenames", rolenames);
	}
	
	public java.lang.String getRolenames() {
		return getStr("rolenames");
	}
	
	public void setWxid(java.lang.String wxid) {
		set("wxid", wxid);
	}
	
	public java.lang.String getWxid() {
		return getStr("wxid");
	}
	
	public void setCid(java.lang.String cid) {
		set("cid", cid);
	}
	
	public java.lang.String getCid() {
		return getStr("cid");
	}
	
	public void setVisiblemobile(java.lang.String visiblemobile) {
		set("visiblemobile", visiblemobile);
	}
	
	public java.lang.String getVisiblemobile() {
		return getStr("visiblemobile");
	}
	
}
