package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSupplier<M extends BaseSupplier<M>> extends Model<M> implements IBean {

	public void setSupplierid(java.lang.String supplierid) {
		set("supplierid", supplierid);
	}
	
	public java.lang.String getSupplierid() {
		return getStr("supplierid");
	}
	
	public void setSuppliercode(java.lang.String suppliercode) {
		set("suppliercode", suppliercode);
	}
	
	public java.lang.String getSuppliercode() {
		return getStr("suppliercode");
	}
	
	public void setSuppliername(java.lang.String suppliername) {
		set("suppliername", suppliername);
	}
	
	public java.lang.String getSuppliername() {
		return getStr("suppliername");
	}
	
	public void setCreditcode(java.lang.String creditcode) {
		set("creditcode", creditcode);
	}
	
	public java.lang.String getCreditcode() {
		return getStr("creditcode");
	}
	
	public void setRegistcapi(java.lang.String registcapi) {
		set("registcapi", registcapi);
	}
	
	public java.lang.String getRegistcapi() {
		return getStr("registcapi");
	}
	
	public void setOpername(java.lang.String opername) {
		set("opername", opername);
	}
	
	public java.lang.String getOpername() {
		return getStr("opername");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}
	
	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}
	
	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}
	
	public java.lang.String getTel() {
		return getStr("tel");
	}
	
	public void setFax(java.lang.String fax) {
		set("fax", fax);
	}
	
	public java.lang.String getFax() {
		return getStr("fax");
	}
	
	public void setScope(java.lang.String scope) {
		set("scope", scope);
	}
	
	public java.lang.String getScope() {
		return getStr("scope");
	}
	
	public void setAdmcode(java.lang.String admcode) {
		set("admcode", admcode);
	}
	
	public java.lang.String getAdmcode() {
		return getStr("admcode");
	}
	
	public void setAdmname(java.lang.String admname) {
		set("admname", admname);
	}
	
	public java.lang.String getAdmname() {
		return getStr("admname");
	}
	
	public void setStartdate(java.util.Date startdate) {
		set("startdate", startdate);
	}
	
	public java.util.Date getStartdate() {
		return get("startdate");
	}
	
	public void setEnddate(java.util.Date enddate) {
		set("enddate", enddate);
	}
	
	public java.util.Date getEnddate() {
		return get("enddate");
	}
	
	public void setLon(java.lang.Double lon) {
		set("lon", lon);
	}
	
	public java.lang.Double getLon() {
		return getDouble("lon");
	}
	
	public void setLat(java.lang.Double lat) {
		set("lat", lat);
	}
	
	public java.lang.Double getLat() {
		return getDouble("lat");
	}
	
	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}
	
	public void setUpdatedate(java.util.Date updatedate) {
		set("updatedate", updatedate);
	}
	
	public java.util.Date getUpdatedate() {
		return get("updatedate");
	}
	
	public void setQdhm(java.lang.String qdhm) {
		set("qdhm", qdhm);
	}
	
	public java.lang.String getQdhm() {
		return getStr("qdhm");
	}
	
	public void setLinkman(java.lang.String linkman) {
		set("linkman", linkman);
	}
	
	public java.lang.String getLinkman() {
		return getStr("linkman");
	}
	
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}
	
	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}
	
}
