package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWf2User<M extends BaseWf2User<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}
	
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}
	
	public void setRoleid(java.lang.String roleid) {
		set("roleid", roleid);
	}
	
	public java.lang.String getRoleid() {
		return getStr("roleid");
	}
	
	public void setRolename(java.lang.String rolename) {
		set("rolename", rolename);
	}
	
	public java.lang.String getRolename() {
		return getStr("rolename");
	}
	
	public void setX(java.lang.Integer x) {
		set("x", x);
	}
	
	public java.lang.Integer getX() {
		return getInt("x");
	}
	
	public void setY(java.lang.Integer y) {
		set("y", y);
	}
	
	public java.lang.Integer getY() {
		return getInt("y");
	}
	
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setAllownext(java.lang.Integer allownext) {
		set("allownext", allownext);
	}
	
	public java.lang.Integer getAllownext() {
		return getInt("allownext");
	}
	
	public void setStartdate(java.util.Date startdate) {
		set("startdate", startdate);
	}
	
	public java.util.Date getStartdate() {
		return get("startdate");
	}
	
	public void setFinishdate(java.util.Date finishdate) {
		set("finishdate", finishdate);
	}
	
	public java.util.Date getFinishdate() {
		return get("finishdate");
	}
	
	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}
	
	public void setWfid(java.lang.String wfid) {
		set("wfid", wfid);
	}
	
	public java.lang.String getWfid() {
		return getStr("wfid");
	}
	
	public void setClientip(java.lang.String clientip) {
		set("clientip", clientip);
	}
	
	public java.lang.String getClientip() {
		return getStr("clientip");
	}
	
	public void setPrjid(java.lang.String prjid) {
		set("prjid", prjid);
	}
	
	public java.lang.String getPrjid() {
		return getStr("prjid");
	}
	
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}
	
}
