package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLot<M extends BaseLot<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setPspid(java.lang.String pspid) {
		set("pspid", pspid);
	}
	
	public java.lang.String getPspid() {
		return getStr("pspid");
	}
	
	public void setLotno(java.lang.String lotno) {
		set("lotno", lotno);
	}
	
	public java.lang.String getLotno() {
		return getStr("lotno");
	}
	
	public void setLotname(java.lang.String lotname) {
		set("lotname", lotname);
	}
	
	public java.lang.String getLotname() {
		return getStr("lotname");
	}
	
	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}
	
	public void setUpdatedate(java.util.Date updatedate) {
		set("updatedate", updatedate);
	}
	
	public java.util.Date getUpdatedate() {
		return get("updatedate");
	}
	
}
