package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFaxDetail<M extends BaseFaxDetail<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}
	
	public void setUpdatedate(java.util.Date updatedate) {
		set("updatedate", updatedate);
	}
	
	public java.util.Date getUpdatedate() {
		return get("updatedate");
	}
	
	public void setBelongid(java.lang.String belongid) {
		set("belongid", belongid);
	}
	
	public java.lang.String getBelongid() {
		return getStr("belongid");
	}
	
	public void setSourceid(java.lang.String sourceid) {
		set("sourceid", sourceid);
	}
	
	public java.lang.String getSourceid() {
		return getStr("sourceid");
	}
	
	public void setIedguid(java.lang.String iedguid) {
		set("iedguid", iedguid);
	}
	
	public java.lang.String getIedguid() {
		return getStr("iedguid");
	}
	
	public void setLotguid(java.lang.String lotguid) {
		set("lotguid", lotguid);
	}
	
	public java.lang.String getLotguid() {
		return getStr("lotguid");
	}
	
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setWjbm(java.lang.String wjbm) {
		set("wjbm", wjbm);
	}
	
	public java.lang.String getWjbm() {
		return getStr("wjbm");
	}
	
	public void setNbbm(java.lang.String nbbm) {
		set("nbbm", nbbm);
	}
	
	public java.lang.String getNbbm() {
		return getStr("nbbm");
	}
	
	public void setWjbt(java.lang.String wjbt) {
		set("wjbt", wjbt);
	}
	
	public java.lang.String getWjbt() {
		return getStr("wjbt");
	}
	
	public void setBbzt(java.lang.String bbzt) {
		set("bbzt", bbzt);
	}
	
	public java.lang.String getBbzt() {
		return getStr("bbzt");
	}
	
	public void setBb(java.lang.String bb) {
		set("bb", bb);
	}
	
	public java.lang.String getBb() {
		return getStr("bb");
	}
	
	public void setYs(java.lang.Integer ys) {
		set("ys", ys);
	}
	
	public java.lang.Integer getYs() {
		return getInt("ys");
	}
	
	public void setZp(java.lang.Integer zp) {
		set("zp", zp);
	}
	
	public java.lang.Integer getZp() {
		return getInt("zp");
	}
	
	public void setDe(java.lang.Integer de) {
		set("de", de);
	}
	
	public java.lang.Integer getDe() {
		return getInt("de");
	}
	
	public void setDr(java.lang.Integer dr) {
		set("dr", dr);
	}
	
	public java.lang.Integer getDr() {
		return getInt("dr");
	}
	
	public void setLb(java.lang.Integer lb) {
		set("lb", lb);
	}
	
	public java.lang.Integer getLb() {
		return getInt("lb");
	}
	
	public void setScjl(java.lang.String scjl) {
		set("scjl", scjl);
	}
	
	public java.lang.String getScjl() {
		return getStr("scjl");
	}
	
	public void setScyj(java.lang.String scyj) {
		set("scyj", scyj);
	}
	
	public java.lang.String getScyj() {
		return getStr("scyj");
	}
	
	public void setMd5(java.lang.String md5) {
		set("md5", md5);
	}
	
	public java.lang.String getMd5() {
		return getStr("md5");
	}
	
	public void setTosap(java.util.Date tosap) {
		set("tosap", tosap);
	}
	
	public java.util.Date getTosap() {
		return get("tosap");
	}
	
	public void setDenbh(java.lang.String denbh) {
		set("denbh", denbh);
	}
	
	public java.lang.String getDenbh() {
		return getStr("denbh");
	}
	
	public void setXbzt(java.lang.String xbzt) {
		set("xbzt", xbzt);
	}
	
	public java.lang.String getXbzt() {
		return getStr("xbzt");
	}
	
	public void setBz(java.lang.String bz) {
		set("bz", bz);
	}
	
	public java.lang.String getBz() {
		return getStr("bz");
	}
	
}
