package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSupplyPlan<M extends BaseSupplyPlan<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setBh(java.lang.String bh) {
		set("bh", bh);
	}
	
	public java.lang.String getBh() {
		return getStr("bh");
	}
	
	public void setTm(java.lang.String tm) {
		set("tm", tm);
	}
	
	public java.lang.String getTm() {
		return getStr("tm");
	}
	
	public void setZw(java.lang.String zw) {
		set("zw", zw);
	}
	
	public java.lang.String getZw() {
		return getStr("zw");
	}
	
	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}
	
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}
	
	public void setPrjid(java.lang.String prjid) {
		set("prjid", prjid);
	}
	
	public java.lang.String getPrjid() {
		return getStr("prjid");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setXh(java.lang.Integer xh) {
		set("xh", xh);
	}
	
	public java.lang.Integer getXh() {
		return getInt("xh");
	}
	
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}
	
	public void setUpdatedate(java.util.Date updatedate) {
		set("updatedate", updatedate);
	}
	
	public java.util.Date getUpdatedate() {
		return get("updatedate");
	}
	
	public void setXczyfzrid(java.lang.String xczyfzrid) {
		set("xczyfzrid", xczyfzrid);
	}
	
	public java.lang.String getXczyfzrid() {
		return getStr("xczyfzrid");
	}
	
	public void setXczyfzr(java.lang.String xczyfzr) {
		set("xczyfzr", xczyfzr);
	}
	
	public java.lang.String getXczyfzr() {
		return getStr("xczyfzr");
	}
	
	public void setXczywz(java.lang.String xczywz) {
		set("xczywz", xczywz);
	}
	
	public java.lang.String getXczywz() {
		return getStr("xczywz");
	}
	
	public void setXczysj(java.util.Date xczysj) {
		set("xczysj", xczysj);
	}
	
	public java.util.Date getXczysj() {
		return get("xczysj");
	}
	
	public void setGlfzrid(java.lang.String glfzrid) {
		set("glfzrid", glfzrid);
	}
	
	public java.lang.String getGlfzrid() {
		return getStr("glfzrid");
	}
	
	public void setGlfzr(java.lang.String glfzr) {
		set("glfzr", glfzr);
	}
	
	public java.lang.String getGlfzr() {
		return getStr("glfzr");
	}
	
	public void setDispatchdate(java.util.Date dispatchdate) {
		set("dispatchdate", dispatchdate);
	}
	
	public java.util.Date getDispatchdate() {
		return get("dispatchdate");
	}
	
	public void setEcbyfzrid(java.lang.String ecbyfzrid) {
		set("ecbyfzrid", ecbyfzrid);
	}
	
	public java.lang.String getEcbyfzrid() {
		return getStr("ecbyfzrid");
	}
	
	public void setEcbyfzr(java.lang.String ecbyfzr) {
		set("ecbyfzr", ecbyfzr);
	}
	
	public java.lang.String getEcbyfzr() {
		return getStr("ecbyfzr");
	}
	
	public void setDeliverremark(java.lang.String deliverremark) {
		set("deliverremark", deliverremark);
	}
	
	public java.lang.String getDeliverremark() {
		return getStr("deliverremark");
	}
	
	public void setDeliverdate(java.util.Date deliverdate) {
		set("deliverdate", deliverdate);
	}
	
	public java.util.Date getDeliverdate() {
		return get("deliverdate");
	}
	
}
