package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLogMsg<M extends BaseLogMsg<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}
	
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}
	
	public void setSendtime(java.util.Date sendtime) {
		set("sendtime", sendtime);
	}
	
	public java.util.Date getSendtime() {
		return get("sendtime");
	}
	
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setHost(java.lang.String host) {
		set("host", host);
	}
	
	public java.lang.String getHost() {
		return getStr("host");
	}
	
	public void setSenderid(java.lang.String senderid) {
		set("senderid", senderid);
	}
	
	public java.lang.String getSenderid() {
		return getStr("senderid");
	}
	
	public void setSendername(java.lang.String sendername) {
		set("sendername", sendername);
	}
	
	public java.lang.String getSendername() {
		return getStr("sendername");
	}
	
	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}
	
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}
	
	public void setHrid(java.lang.String hrid) {
		set("hrid", hrid);
	}
	
	public java.lang.String getHrid() {
		return getStr("hrid");
	}
	
	public void setBelongid(java.lang.String belongid) {
		set("belongid", belongid);
	}
	
	public java.lang.String getBelongid() {
		return getStr("belongid");
	}
	
	public void setWfid(java.lang.String wfid) {
		set("wfid", wfid);
	}
	
	public java.lang.String getWfid() {
		return getStr("wfid");
	}
	
	public void setPrjid(java.lang.String prjid) {
		set("prjid", prjid);
	}
	
	public java.lang.String getPrjid() {
		return getStr("prjid");
	}
	
	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}
	
	public void setResult(java.lang.String result) {
		set("result", result);
	}
	
	public java.lang.String getResult() {
		return getStr("result");
	}
	
	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}
	
	public void setUpdatedate(java.util.Date updatedate) {
		set("updatedate", updatedate);
	}
	
	public java.util.Date getUpdatedate() {
		return get("updatedate");
	}
	
	public void setNid(java.lang.String nid) {
		set("nid", nid);
	}
	
	public java.lang.String getNid() {
		return getStr("nid");
	}
	
}
