package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGfDetail<M extends BaseGfDetail<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setPid(java.lang.String pid) {
		set("pid", pid);
	}
	
	public java.lang.String getPid() {
		return getStr("pid");
	}
	
	public void setXh(java.lang.Integer xh) {
		set("xh", xh);
	}
	
	public java.lang.Integer getXh() {
		return getInt("xh");
	}
	
	public void setMc(java.lang.String mc) {
		set("mc", mc);
	}
	
	public java.lang.String getMc() {
		return getStr("mc");
	}
	
	public void setPrjid(java.lang.String prjid) {
		set("prjid", prjid);
	}
	
	public java.lang.String getPrjid() {
		return getStr("prjid");
	}
	
	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}
	
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}
	
	public void setFwbh(java.lang.String fwbh) {
		set("fwbh", fwbh);
	}
	
	public java.lang.String getFwbh() {
		return getStr("fwbh");
	}
	
	public void setPrevtask(java.lang.String prevtask) {
		set("prevtask", prevtask);
	}
	
	public java.lang.String getPrevtask() {
		return getStr("prevtask");
	}
	
	public void setSourceid(java.lang.String sourceid) {
		set("sourceid", sourceid);
	}
	
	public java.lang.String getSourceid() {
		return getStr("sourceid");
	}
	
	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}
	
	public void setUpdatedate(java.util.Date updatedate) {
		set("updatedate", updatedate);
	}
	
	public java.util.Date getUpdatedate() {
		return get("updatedate");
	}
	
}
