package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProject<M extends BaseProject<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setPspid(java.lang.String pspid) {
		set("pspid", pspid);
	}
	
	public java.lang.String getPspid() {
		return getStr("pspid");
	}
	
	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}
	
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}
	
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public void setCid(java.lang.String cid) {
		set("cid", cid);
	}
	
	public java.lang.String getCid() {
		return getStr("cid");
	}
	
	public void setCname(java.lang.String cname) {
		set("cname", cname);
	}
	
	public java.lang.String getCname() {
		return getStr("cname");
	}
	
	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}
	
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}
	
	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}
	
	public void setUpdatedate(java.util.Date updatedate) {
		set("updatedate", updatedate);
	}
	
	public java.util.Date getUpdatedate() {
		return get("updatedate");
	}
	
	public void setEngineeringid(java.lang.String engineeringid) {
		set("engineeringid", engineeringid);
	}
	
	public java.lang.String getEngineeringid() {
		return getStr("engineeringid");
	}
	
	public void setAdmcode(java.lang.Integer admcode) {
		set("admcode", admcode);
	}
	
	public java.lang.Integer getAdmcode() {
		return getInt("admcode");
	}
	
	public void setSystypes(java.lang.String systypes) {
		set("systypes", systypes);
	}
	
	public java.lang.String getSystypes() {
		return getStr("systypes");
	}
	
	public void setCpmsPrjid(java.lang.String cpmsPrjid) {
		set("cpms_prjid", cpmsPrjid);
	}
	
	public java.lang.String getCpmsPrjid() {
		return getStr("cpms_prjid");
	}
	
}
