package com.demo.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_bx", "id", Bx.class);
		arp.addMapping("t_company", "id", Company.class);
		arp.addMapping("t_doc", "id", Doc.class);
		arp.addMapping("t_doc_detail", "id", DocDetail.class);
		arp.addMapping("t_doc_share", "id", DocShare.class);
		arp.addMapping("t_doc_tree", "id", DocTree.class);
		arp.addMapping("t_email", "id", Email.class);
		arp.addMapping("t_fax", "id", Fax.class);
		arp.addMapping("t_fax_cs", "id", FaxCs.class);
		arp.addMapping("t_fax_detail", "id", FaxDetail.class);
		arp.addMapping("t_fax_gf", "id", FaxGf.class);
		arp.addMapping("t_file", "fileid", File.class);
		arp.addMapping("t_file_download_log", "id", FileDownloadLog.class);
		arp.addMapping("t_gf_allow", "id", GfAllow.class);
		arp.addMapping("t_gf_detail", "id", GfDetail.class);
		arp.addMapping("t_gf_detail_task", "id", GfDetailTask.class);
		arp.addMapping("t_gf_task", "id", GfTask.class);
		arp.addMapping("t_idcard", "id", Idcard.class);
		arp.addMapping("t_idcard_log", "id", IdcardLog.class);
		arp.addMapping("t_log_msg", "id", LogMsg.class);
		arp.addMapping("t_log_msg_detail", "id", LogMsgDetail.class);
		arp.addMapping("t_login_log", "id", LoginLog.class);
		arp.addMapping("t_lot", "id", Lot.class);
		arp.addMapping("t_mrp_jh", "id", MrpJh.class);
		arp.addMapping("t_mrp_jh_detail", "id", MrpJhDetail.class);
		arp.addMapping("t_news", "id", News.class);
		arp.addMapping("t_pd", "id", Pd.class);
		arp.addMapping("t_pd_allow", "id", PdAllow.class);
		arp.addMapping("t_pd_cs", "id", PdCs.class);
		arp.addMapping("t_pd_share", "id", PdShare.class);
		arp.addMapping("t_pd_share_detail", "id", PdShareDetail.class);
		arp.addMapping("t_pd_share_log", "id", PdShareLog.class);
		arp.addMapping("t_pdm", "id", Pdm.class);
		arp.addMapping("t_pdm_doc", "id", PdmDoc.class);
		arp.addMapping("t_pdm_type", "fldm", PdmType.class);
		arp.addMapping("t_prj", "prjid", Prj.class);
		arp.addMapping("t_prjuser", "id", Prjuser.class);
		arp.addMapping("t_prjuser_group", "id", PrjuserGroup.class);
		arp.addMapping("t_project", "id", Project.class);
		arp.addMapping("t_project_type", "id", ProjectType.class);
		arp.addMapping("t_sign", "id", Sign.class);
		arp.addMapping("t_submit_log", "id", SubmitLog.class);
		arp.addMapping("t_supplier", "supplierid", Supplier.class);
		arp.addMapping("t_supplier_favorite", "id", SupplierFavorite.class);
		arp.addMapping("t_supplier_linkman", "id", SupplierLinkman.class);
		arp.addMapping("t_supplier_lot", "id", SupplierLot.class);
		arp.addMapping("t_supplier_type", "dm", SupplierType.class);
		arp.addMapping("t_supplier_user", "id", SupplierUser.class);
		arp.addMapping("t_supply_plan", "id", SupplyPlan.class);
		arp.addMapping("t_supply_plan_detail", "id", SupplyPlanDetail.class);
		arp.addMapping("t_sys_page", "pageid", SysPage.class);
		arp.addMapping("t_sys_project", "id", SysProject.class);
		arp.addMapping("t_sys_role", "id", SysRole.class);
		arp.addMapping("t_sys_site", "id", SysSite.class);
		arp.addMapping("t_todotask", "id", Todotask.class);
		arp.addMapping("t_user", "userid", User.class);
		arp.addMapping("t_user_favorite", "id", UserFavorite.class);
		arp.addMapping("t_user_prj", "id", UserPrj.class);
		arp.addMapping("t_user_project", "id", UserProject.class);
		arp.addMapping("t_user_role", "id", UserRole.class);
		arp.addMapping("t_user_wx", "id", UserWx.class);
		arp.addMapping("t_wf", "id", Wf.class);
		arp.addMapping("t_wf_type", "typeid", WfType.class);
		arp.addMapping("t_wf_urge", "id", WfUrge.class);
		arp.addMapping("t_wf2", "id", Wf2.class);
		arp.addMapping("t_wf2_notify", "id", Wf2Notify.class);
		arp.addMapping("t_wf2_tpl", "id", Wf2Tpl.class);
		arp.addMapping("t_wf2_tpl_detail", "id", Wf2TplDetail.class);
		arp.addMapping("t_wf2_user", "id", Wf2User.class);
		arp.addMapping("t_wfdata", "id", Wfdata.class);
		arp.addMapping("t_wx_dept", "id", WxDept.class);
		arp.addMapping("t_wx_doc", "id", WxDoc.class);
		arp.addMapping("t_wx_guest", "id", WxGuest.class);
		arp.addMapping("t_wx_role", "id", WxRole.class);
		arp.addMapping("t_wx_user", "userid", WxUser.class);
		arp.addMapping("t_wx_user_dept", "id", WxUserDept.class);
		arp.addMapping("t_wx_user_role", "id", WxUserRole.class);
	}
}

