package com.demo.common.model;

import com.demo.common.model.base.BaseDocShare;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DocShare extends BaseDocShare<DocShare> {
	
}
