package com.demo.common.model;

import com.demo.common.model.base.BaseFaxDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FaxDetail extends BaseFaxDetail<FaxDetail> {
	
}
