package com.demo.common.model;

import com.demo.common.model.base.BaseFileDownloadLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FileDownloadLog extends BaseFileDownloadLog<FileDownloadLog> {
	
}
