package com.demo.common.model;

import com.demo.common.model.base.BaseGfDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GfDetail extends BaseGfDetail<GfDetail> {
	
}
