package com.demo.common.model;

import com.demo.common.model.base.BaseGfDetailTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GfDetailTask extends BaseGfDetailTask<GfDetailTask> {
	
}
