package com.demo.common.model;

import com.demo.common.model.base.BaseIdcardLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IdcardLog extends BaseIdcardLog<IdcardLog> {
	
}
