package com.demo.common.model;

import com.demo.common.model.base.BaseLogMsgDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogMsgDetail extends BaseLogMsgDetail<LogMsgDetail> {
	
}
