package com.demo.common.model;

import com.demo.common.model.base.BaseMrpJhDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MrpJhDetail extends BaseMrpJhDetail<MrpJhDetail> {
	
}
