package com.demo.common.model;

import com.demo.common.model.base.BasePdShareDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PdShareDetail extends BasePdShareDetail<PdShareDetail> {
	
}
