package com.demo.common.model;

import com.demo.common.model.base.BasePdShareLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PdShareLog extends BasePdShareLog<PdShareLog> {
	
}
