package com.demo.common.model;

import com.demo.common.model.base.BasePrjuserGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PrjuserGroup extends BasePrjuserGroup<PrjuserGroup> {
	
}
