package com.demo.common.model;

import com.demo.common.model.base.BaseProjectType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectType extends BaseProjectType<ProjectType> {
	
}
