package com.demo.common.model;

import com.demo.common.model.base.BaseSubmitLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SubmitLog extends BaseSubmitLog<SubmitLog> {
	
}
