package com.demo.common.model;

import com.demo.common.model.base.BaseSupplierType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplierType extends BaseSupplierType<SupplierType> {
	
}
