package com.demo.common.model;

import com.demo.common.model.base.BaseSupplyPlan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplyPlan extends BaseSupplyPlan<SupplyPlan> {
	
}
