package com.demo.common.model;

import com.demo.common.model.base.BaseSupplyPlanDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplyPlanDetail extends BaseSupplyPlanDetail<SupplyPlanDetail> {
	
}
