package com.demo.common.model;

import com.demo.common.model.base.BaseSupplierUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplierUser extends BaseSupplierUser<SupplierUser> {
	
}
