package com.demo.common.model;

import com.demo.common.model.base.BaseSupplierLinkman;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplierLinkman extends BaseSupplierLinkman<SupplierLinkman> {
	
}
