package com.demo.common.model;

import com.demo.common.model.base.BaseSupplierLot;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplierLot extends BaseSupplierLot<SupplierLot> {
	
}
