package com.demo.common.model;

import com.demo.common.model.base.BaseSupplierFavorite;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplierFavorite extends BaseSupplierFavorite<SupplierFavorite> {
	
}
