package com.demo.common.model;

import com.demo.common.model.base.BaseSysProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysProject extends BaseSysProject<SysProject> {
	
}
