package com.demo.common.model;

import com.demo.common.model.base.BaseTodotask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Todotask extends BaseTodotask<Todotask> {
	
}
