package com.demo.common.model;

import com.demo.common.model.base.BaseUserFavorite;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserFavorite extends BaseUserFavorite<UserFavorite> {
	
}
