package com.demo.common.model;

import com.demo.common.model.base.BaseUserProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserProject extends BaseUserProject<UserProject> {
	
}
