package com.demo.common.model;

import com.demo.common.model.base.BaseWf2Notify;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Wf2Notify extends BaseWf2Notify<Wf2Notify> {
	
}
