package com.demo.common.model;

import com.demo.common.model.base.BaseWf2TplDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Wf2TplDetail extends BaseWf2TplDetail<Wf2TplDetail> {
	
}
