package com.demo.common.model;

import com.demo.common.model.base.BaseWxUserDept;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxUserDept extends BaseWxUserDept<WxUserDept> {
	
}
