package com.demo.common.model;

import com.demo.common.model.base.BaseWxUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxUserRole extends BaseWxUserRole<WxUserRole> {
	
}
